# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pdcp/criticality_level.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pdcp/criticality_level.proto',
  package='pb.pdcp.criticality_level',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1cpdcp/criticality_level.proto\x12\x19pb.pdcp.criticality_level*s\n\x10\x43riticalityLevel\x12\x18\n\x14PDC_CRIT_LVL_OUTSIDE\x10\x00\x12\x16\n\x12PDC_CRIT_LVL_GREEN\x10\x01\x12\x17\n\x13PDC_CRIT_LVL_YELLOW\x10\x02\x12\x14\n\x10PDC_CRIT_LVL_RED\x10\x03'
)

_CRITICALITYLEVEL = _descriptor.EnumDescriptor(
  name='CriticalityLevel',
  full_name='pb.pdcp.criticality_level.CriticalityLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PDC_CRIT_LVL_OUTSIDE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PDC_CRIT_LVL_GREEN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PDC_CRIT_LVL_YELLOW', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PDC_CRIT_LVL_RED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=59,
  serialized_end=174,
)
_sym_db.RegisterEnumDescriptor(_CRITICALITYLEVEL)

CriticalityLevel = enum_type_wrapper.EnumTypeWrapper(_CRITICALITYLEVEL)
PDC_CRIT_LVL_OUTSIDE = 0
PDC_CRIT_LVL_GREEN = 1
PDC_CRIT_LVL_YELLOW = 2
PDC_CRIT_LVL_RED = 3


DESCRIPTOR.enum_types_by_name['CriticalityLevel'] = _CRITICALITYLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
