# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ap_psm_app/engine_req.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ap_commonvehsigprovider import start_stop_status_pb2 as ap__commonvehsigprovider_dot_start__stop__status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ap_psm_app/engine_req.proto',
  package='pb.ap_psm_app.engine_req',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1b\x61p_psm_app/engine_req.proto\x12\x18pb.ap_psm_app.engine_req\x1a/ap_commonvehsigprovider/start_stop_status.proto\"\x98\x01\n\tEngineReq\x12\x16\n\rstopEngine_nu\x18\xf3\x13 \x01(\x08\x12\x17\n\x0estartEngine_nu\x18\x8a\x05 \x01(\x08\x12Z\n\x12startStopStatus_nu\x18\x9c\x05 \x01(\x0e\x32=.pb.ap_commonvehsigprovider.start_stop_status.StartStopStatus\"J\n\x14\x45ngineReq_array_port\x12\x32\n\x04\x64\x61ta\x18\xc8\x13 \x03(\x0b\x32#.pb.ap_psm_app.engine_req.EngineReq'
  ,
  dependencies=[ap__commonvehsigprovider_dot_start__stop__status__pb2.DESCRIPTOR,])




_ENGINEREQ = _descriptor.Descriptor(
  name='EngineReq',
  full_name='pb.ap_psm_app.engine_req.EngineReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stopEngine_nu', full_name='pb.ap_psm_app.engine_req.EngineReq.stopEngine_nu', index=0,
      number=2547, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startEngine_nu', full_name='pb.ap_psm_app.engine_req.EngineReq.startEngine_nu', index=1,
      number=650, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startStopStatus_nu', full_name='pb.ap_psm_app.engine_req.EngineReq.startStopStatus_nu', index=2,
      number=668, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=259,
)


_ENGINEREQ_ARRAY_PORT = _descriptor.Descriptor(
  name='EngineReq_array_port',
  full_name='pb.ap_psm_app.engine_req.EngineReq_array_port',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='pb.ap_psm_app.engine_req.EngineReq_array_port.data', index=0,
      number=2504, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=335,
)

_ENGINEREQ.fields_by_name['startStopStatus_nu'].enum_type = ap__commonvehsigprovider_dot_start__stop__status__pb2._STARTSTOPSTATUS
_ENGINEREQ_ARRAY_PORT.fields_by_name['data'].message_type = _ENGINEREQ
DESCRIPTOR.message_types_by_name['EngineReq'] = _ENGINEREQ
DESCRIPTOR.message_types_by_name['EngineReq_array_port'] = _ENGINEREQ_ARRAY_PORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EngineReq = _reflection.GeneratedProtocolMessageType('EngineReq', (_message.Message,), {
  'DESCRIPTOR' : _ENGINEREQ,
  '__module__' : 'ap_psm_app.engine_req_pb2'
  # @@protoc_insertion_point(class_scope:pb.ap_psm_app.engine_req.EngineReq)
  })
_sym_db.RegisterMessage(EngineReq)

EngineReq_array_port = _reflection.GeneratedProtocolMessageType('EngineReq_array_port', (_message.Message,), {
  'DESCRIPTOR' : _ENGINEREQ_ARRAY_PORT,
  '__module__' : 'ap_psm_app.engine_req_pb2'
  # @@protoc_insertion_point(class_scope:pb.ap_psm_app.engine_req.EngineReq_array_port)
  })
_sym_db.RegisterMessage(EngineReq_array_port)


# @@protoc_insertion_point(module_scope)
