# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hpsd/platform_state.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hpsd/platform_state.proto',
  package='pb.hpsd.platform_state',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x19hpsd/platform_state.proto\x12\x16pb.hpsd.platform_state*N\n\rPlatformState\x12\x0b\n\x07STARTUP\x10\x00\x12\x0c\n\x08\x46\x41ST_PDW\x10\x01\x12\x14\n\x10NORMAL_OPERATION\x10\x02\x12\x0c\n\x08SHUTDOWN\x10\x03'
)

_PLATFORMSTATE = _descriptor.EnumDescriptor(
  name='PlatformState',
  full_name='pb.hpsd.platform_state.PlatformState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STARTUP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAST_PDW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NORMAL_OPERATION', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=53,
  serialized_end=131,
)
_sym_db.RegisterEnumDescriptor(_PLATFORMSTATE)

PlatformState = enum_type_wrapper.EnumTypeWrapper(_PLATFORMSTATE)
STARTUP = 0
FAST_PDW = 1
NORMAL_OPERATION = 2
SHUTDOWN = 3


DESCRIPTOR.enum_types_by_name['PlatformState'] = _PLATFORMSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
