# general
name: SEF_Brake
type: project
license: Continental Teves AG & Co. oHG; all rights reserved
major_version: 1
description: A surrogate model designed to be used in the VSP of ADAS Driving Functions
schema_version: 2

options:
    SEF_BRAKE:
        type: string
        enum:
            - "OCTAGON"
            - "SMOKE_TEST"
    CM_BUILD:
        type: boolean
        enum:
            - true
            - false
    MoCo_Brake:
        type: boolean
        enum:
            - true
            - false
    Enable_CT:
        type: boolean
        enum:
            - true
            - false
variants:
    OCTAGON:
        production:
            platforms:
                - build: vs2017
                - build: vs2017_debug
                - build: ubuntu_20_04_x86_64-release
            components: &alias_components
                - TARGET_COMPONENT
            options: &alias_options
                SEF_BRAKE: "OCTAGON"
                CM_BUILD: true
                MoCo_Brake: false
                Enable_CT: false
            uses: &alias_uses
               carmaker:
                 release: 10.2.1-release8
                 variant: external
                 conan:
                   user: 3rdparty
                   channel: releases

    # SMOKE_TEST:
        # production:
            # platforms:
                # - build: vs2017
            # components:
                # - TARGET_COMPONENT
            # options: &alias_options_vCEM
                # SEF_BRAKE: "SMOKE_TEST"
                # CM_BUILD: true
                # MoCo_Brake: false
                # Enable_CT: true
            # uses: *alias_uses
