# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ap_psm/unexpected_event.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ap_psm/unexpected_event.proto',
  package='pb.ap_psm.unexpected_event',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1d\x61p_psm/unexpected_event.proto\x12\x1apb.ap_psm.unexpected_event*A\n\x0fUnexpectedEvent\x12\x0c\n\x08NO_EVENT\x10\x00\x12 \n\x1c\x44RIVER_STEERING_INTERVENTION\x10\x01'
)

_UNEXPECTEDEVENT = _descriptor.EnumDescriptor(
  name='UnexpectedEvent',
  full_name='pb.ap_psm.unexpected_event.UnexpectedEvent',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_EVENT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRIVER_STEERING_INTERVENTION', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=61,
  serialized_end=126,
)
_sym_db.RegisterEnumDescriptor(_UNEXPECTEDEVENT)

UnexpectedEvent = enum_type_wrapper.EnumTypeWrapper(_UNEXPECTEDEVENT)
NO_EVENT = 0
DRIVER_STEERING_INTERVENTION = 1


DESCRIPTOR.enum_types_by_name['UnexpectedEvent'] = _UNEXPECTEDEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
