// Attention, this file is generated by Cobolt from template: C:\_repos\mf_sil\dbg\eco\eco.generic\codegen\templates\types\struct.h.template!

#ifdef ECO_C_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C and C++ types mixed
  #endif
#endif
#ifdef ECO_CPP14_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C++ and C++14 types mixed
  #endif
#endif
#define ECO_CPP_TYPES_USED

#ifndef US_DRV_US_DRV_RUNTIME_SENSOR_CONFIGURATION_H_
#define US_DRV_US_DRV_RUNTIME_SENSOR_CONFIGURATION_H_

#include "us_drv/us_drv_sensor_mode.h"
#include "Platform_Types.h"
#include "eco/memset.h"


namespace us_drv
{

  struct UsDrvRuntimeSensorConfiguration
  {
    UsDrvSensorMode state;
    uint8 stochasticCodes_ms[8];
    uint8 firingSchemes[8];
    uint8 firCoefficientSet;
    uint8 receiveGain;
    uint8 advancedPathConfiguration;
    uint8 aatgConfiguration1;
    uint8 aatgConfiguration2;
    uint8 adaptiveThresholdGeneration;
    uint8 swVersionMajor;
    uint8 swVersionMinor;
    uint8 hwVersionMajor;
    uint8 hwVersionMinor;
    uint32 serialNumber;
  };

  inline ::us_drv::UsDrvRuntimeSensorConfiguration createUsDrvRuntimeSensorConfiguration()
  {
    UsDrvRuntimeSensorConfiguration m;
    (void)::eco::memset(&m, 0U, sizeof(UsDrvRuntimeSensorConfiguration));
    return m;
  }

} // namespace us_drv

namespace eco
{
  template<class T>
  inline T create_default();

  template<>
  inline ::us_drv::UsDrvRuntimeSensorConfiguration create_default()
  {
      return ::us_drv::createUsDrvRuntimeSensorConfiguration();
  }
}


#endif // US_DRV_US_DRV_RUNTIME_SENSOR_CONFIGURATION_H_
