// Attention, this file is generated by Cobolt from template: D:\.bbs_conan\c029a0\1\codegen\templates\types_14\enum.h.template!

#ifdef ECO_C_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C and C++14 types mixed
  #endif
#endif
#ifdef ECO_CPP_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C++ and C++14 types mixed
  #endif
#endif
#define ECO_CPP14_TYPES_USED

#ifndef AP_COMMONVEHSIGPROVIDER_GEAR_BOX_CTRL_SYSTEM_STATE_H_
#define AP_COMMONVEHSIGPROVIDER_GEAR_BOX_CTRL_SYSTEM_STATE_H_

#include "Platform_Types.h"

namespace ap_commonvehsigprovider
{
  ///System status/Availability of the gearbox control.
  enum class GearBoxCtrlSystemState : uint8
  {
      GCTRL_NOT_AVAILABLE = 0U,
      GCTRL_INITIALISATION = 1U,
      GCTRL_AVAILABLE = 2U,
      GCTRL_ERROR = 7U,
  };
} // namespace ap_commonvehsigprovider
#endif // AP_COMMONVEHSIGPROVIDER_GEAR_BOX_CTRL_SYSTEM_STATE_H_
