#!/usr/bin/env groovy

pipeline {
    agent { label 'windows' }
    stages {
        stage("Init environment"){
            steps {
                script {
                    bat(
                        script: """C:/Python37/python.exe -m venv .venv
                            call .venv/Scripts/activate
                            python -m pip install --upgrade pip
                            python -m pip install -r requirements_dev.txt
                        """
                    )
                }
            }
        }

     	stage('Build Wheel') {
            steps {
                script {
                    bat(
                        script: """call scripts/build_wheel.bat
                        """
                    )
                }
            }
        }

        stage('Upload Python Wheel to Artifactory') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: "artifactory_pypi", usernameVariable: "PYPI_USER", passwordVariable: "PYPI_TOKEN")]) {
                        if(env.TAG_NAME) {
                            bat('call .venv/Scripts/activate && twine upload --repository-url https://eu.artifactory.conti.de/artifactory/api/pypi/c_adas_cip_pypi_l -u %PYPI_USER% -p %PYPI_TOKEN% dist/*.whl')
                        } else {
                            echo("Not a tag! Wheel locally saved!")
                            archiveArtifacts(artifacts: 'dist/*.whl', followSymlinks: false)
                        }
                    }
                }
            }
        }
    }

    post {
        cleanup {
            cleanWs()
        }
    }
}