// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ap_psm_app/fc_parksm_params.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "eco/signal_header.pb.h"
#include "ap_common/fc_parksm_sys_func_params.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto;
namespace pb {
namespace ap_psm_app {
namespace fc_parksm_params {
class FC_PARKSM_Params;
class FC_PARKSM_ParamsDefaultTypeInternal;
extern FC_PARKSM_ParamsDefaultTypeInternal _FC_PARKSM_Params_default_instance_;
class FC_PARKSM_Params_array_port;
class FC_PARKSM_Params_array_portDefaultTypeInternal;
extern FC_PARKSM_Params_array_portDefaultTypeInternal _FC_PARKSM_Params_array_port_default_instance_;
}  // namespace fc_parksm_params
}  // namespace ap_psm_app
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params* Arena::CreateMaybeMessage<::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params>(Arena*);
template<> ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params_array_port* Arena::CreateMaybeMessage<::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params_array_port>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {
namespace ap_psm_app {
namespace fc_parksm_params {

// ===================================================================

class FC_PARKSM_Params :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params) */ {
 public:
  FC_PARKSM_Params();
  virtual ~FC_PARKSM_Params();

  FC_PARKSM_Params(const FC_PARKSM_Params& from);
  FC_PARKSM_Params(FC_PARKSM_Params&& from) noexcept
    : FC_PARKSM_Params() {
    *this = ::std::move(from);
  }

  inline FC_PARKSM_Params& operator=(const FC_PARKSM_Params& from) {
    CopyFrom(from);
    return *this;
  }
  inline FC_PARKSM_Params& operator=(FC_PARKSM_Params&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FC_PARKSM_Params& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FC_PARKSM_Params* internal_default_instance() {
    return reinterpret_cast<const FC_PARKSM_Params*>(
               &_FC_PARKSM_Params_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FC_PARKSM_Params& a, FC_PARKSM_Params& b) {
    a.Swap(&b);
  }
  inline void Swap(FC_PARKSM_Params* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FC_PARKSM_Params* New() const final {
    return CreateMaybeMessage<FC_PARKSM_Params>(nullptr);
  }

  FC_PARKSM_Params* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FC_PARKSM_Params>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FC_PARKSM_Params& from);
  void MergeFrom(const FC_PARKSM_Params& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FC_PARKSM_Params* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto);
    return ::descriptor_table_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSSigHeaderFieldNumber = 1033,
    kSysFuncParamsFieldNumber = 3021,
    kAPSOVERSHOOTDISTTHRESHMFieldNumber = 311,
    kAPSUNDERSHOOTDISTTHRESHMFieldNumber = 807,
    kAPSNUMIGNOREDREMALIVENUFieldNumber = 963,
    kAPSCHECKPDCSYSTEMSTATENUFieldNumber = 2177,
    kAPSDONOTCHECKREMKEYNUFieldNumber = 555,
    kAPSRESETMAPDISTMFieldNumber = 1506,
    kAPSNUMIGNOREDKEYALIVENUFieldNumber = 1517,
    kAPSBRAKEPERSSTHRESHCBARFieldNumber = 1702,
    kUiVersionNumberFieldNumber = 2124,
    kAPSAPPRESYNUFieldNumber = 2228,
    kAPSMINAPPENERGYLEVELPERCFieldNumber = 2647,
    kAPSCONFIRMATIONTIMESFieldNumber = 2962,
    kAPSBRAKEPERSSTHRESHPBARFieldNumber = 3118,
    kAPSREMFINGERMOVEDELAYUSFieldNumber = 3434,
    kAPSREMFINGERMOVTHRESHPXFieldNumber = 3512,
    kAPSAPPRESXNUFieldNumber = 3584,
    kAPSSTEERINGTORQUETHRESHNMFieldNumber = 3601,
    kAPSDEADMANSWITCHTHRESHOLDTIMERSFieldNumber = 3822,
    kAPSSTOPDISTTHRESHMFieldNumber = 3902,
  };
  // optional .pb.eco.signal_header.SignalHeader sSigHeader = 1033;
  bool has_ssigheader() const;
  private:
  bool _internal_has_ssigheader() const;
  public:
  void clear_ssigheader();
  const ::pb::eco::signal_header::SignalHeader& ssigheader() const;
  ::pb::eco::signal_header::SignalHeader* release_ssigheader();
  ::pb::eco::signal_header::SignalHeader* mutable_ssigheader();
  void set_allocated_ssigheader(::pb::eco::signal_header::SignalHeader* ssigheader);
  private:
  const ::pb::eco::signal_header::SignalHeader& _internal_ssigheader() const;
  ::pb::eco::signal_header::SignalHeader* _internal_mutable_ssigheader();
  public:

  // optional .pb.ap_common.fc_parksm_sys_func_params.FC_PARKSM_Sys_Func_Params sysFuncParams = 3021;
  bool has_sysfuncparams() const;
  private:
  bool _internal_has_sysfuncparams() const;
  public:
  void clear_sysfuncparams();
  const ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params& sysfuncparams() const;
  ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* release_sysfuncparams();
  ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* mutable_sysfuncparams();
  void set_allocated_sysfuncparams(::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* sysfuncparams);
  private:
  const ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params& _internal_sysfuncparams() const;
  ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* _internal_mutable_sysfuncparams();
  public:

  // optional float AP_S_OVERSHOOT_DIST_THRESH_M = 311;
  bool has_ap_s_overshoot_dist_thresh_m() const;
  private:
  bool _internal_has_ap_s_overshoot_dist_thresh_m() const;
  public:
  void clear_ap_s_overshoot_dist_thresh_m();
  float ap_s_overshoot_dist_thresh_m() const;
  void set_ap_s_overshoot_dist_thresh_m(float value);
  private:
  float _internal_ap_s_overshoot_dist_thresh_m() const;
  void _internal_set_ap_s_overshoot_dist_thresh_m(float value);
  public:

  // optional float AP_S_UNDERSHOOT_DIST_THRESH_M = 807;
  bool has_ap_s_undershoot_dist_thresh_m() const;
  private:
  bool _internal_has_ap_s_undershoot_dist_thresh_m() const;
  public:
  void clear_ap_s_undershoot_dist_thresh_m();
  float ap_s_undershoot_dist_thresh_m() const;
  void set_ap_s_undershoot_dist_thresh_m(float value);
  private:
  float _internal_ap_s_undershoot_dist_thresh_m() const;
  void _internal_set_ap_s_undershoot_dist_thresh_m(float value);
  public:

  // optional uint32 AP_S_NUM_IGNORED_REM_ALIVE_NU = 963;
  bool has_ap_s_num_ignored_rem_alive_nu() const;
  private:
  bool _internal_has_ap_s_num_ignored_rem_alive_nu() const;
  public:
  void clear_ap_s_num_ignored_rem_alive_nu();
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_num_ignored_rem_alive_nu() const;
  void set_ap_s_num_ignored_rem_alive_nu(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ap_s_num_ignored_rem_alive_nu() const;
  void _internal_set_ap_s_num_ignored_rem_alive_nu(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional bool AP_S_CHECK_PDC_SYSTEM_STATE_NU = 2177;
  bool has_ap_s_check_pdc_system_state_nu() const;
  private:
  bool _internal_has_ap_s_check_pdc_system_state_nu() const;
  public:
  void clear_ap_s_check_pdc_system_state_nu();
  bool ap_s_check_pdc_system_state_nu() const;
  void set_ap_s_check_pdc_system_state_nu(bool value);
  private:
  bool _internal_ap_s_check_pdc_system_state_nu() const;
  void _internal_set_ap_s_check_pdc_system_state_nu(bool value);
  public:

  // optional bool AP_S_DO_NOT_CHECK_REM_KEY_NU = 555;
  bool has_ap_s_do_not_check_rem_key_nu() const;
  private:
  bool _internal_has_ap_s_do_not_check_rem_key_nu() const;
  public:
  void clear_ap_s_do_not_check_rem_key_nu();
  bool ap_s_do_not_check_rem_key_nu() const;
  void set_ap_s_do_not_check_rem_key_nu(bool value);
  private:
  bool _internal_ap_s_do_not_check_rem_key_nu() const;
  void _internal_set_ap_s_do_not_check_rem_key_nu(bool value);
  public:

  // optional float AP_S_RESET_MAP_DIST_M = 1506;
  bool has_ap_s_reset_map_dist_m() const;
  private:
  bool _internal_has_ap_s_reset_map_dist_m() const;
  public:
  void clear_ap_s_reset_map_dist_m();
  float ap_s_reset_map_dist_m() const;
  void set_ap_s_reset_map_dist_m(float value);
  private:
  float _internal_ap_s_reset_map_dist_m() const;
  void _internal_set_ap_s_reset_map_dist_m(float value);
  public:

  // optional uint32 AP_S_NUM_IGNORED_KEY_ALIVE_NU = 1517;
  bool has_ap_s_num_ignored_key_alive_nu() const;
  private:
  bool _internal_has_ap_s_num_ignored_key_alive_nu() const;
  public:
  void clear_ap_s_num_ignored_key_alive_nu();
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_num_ignored_key_alive_nu() const;
  void set_ap_s_num_ignored_key_alive_nu(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ap_s_num_ignored_key_alive_nu() const;
  void _internal_set_ap_s_num_ignored_key_alive_nu(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional float AP_S_BRAKE_PERSS_THRESH_C_BAR = 1702;
  bool has_ap_s_brake_perss_thresh_c_bar() const;
  private:
  bool _internal_has_ap_s_brake_perss_thresh_c_bar() const;
  public:
  void clear_ap_s_brake_perss_thresh_c_bar();
  float ap_s_brake_perss_thresh_c_bar() const;
  void set_ap_s_brake_perss_thresh_c_bar(float value);
  private:
  float _internal_ap_s_brake_perss_thresh_c_bar() const;
  void _internal_set_ap_s_brake_perss_thresh_c_bar(float value);
  public:

  // optional uint32 uiVersionNumber = 2124;
  bool has_uiversionnumber() const;
  private:
  bool _internal_has_uiversionnumber() const;
  public:
  void clear_uiversionnumber();
  ::PROTOBUF_NAMESPACE_ID::uint32 uiversionnumber() const;
  void set_uiversionnumber(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_uiversionnumber() const;
  void _internal_set_uiversionnumber(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 AP_S_APP_RES_Y_NU = 2228;
  bool has_ap_s_app_res_y_nu() const;
  private:
  bool _internal_has_ap_s_app_res_y_nu() const;
  public:
  void clear_ap_s_app_res_y_nu();
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_app_res_y_nu() const;
  void set_ap_s_app_res_y_nu(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ap_s_app_res_y_nu() const;
  void _internal_set_ap_s_app_res_y_nu(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 AP_S_MIN_APP_ENERGY_LEVEL_PERC = 2647;
  bool has_ap_s_min_app_energy_level_perc() const;
  private:
  bool _internal_has_ap_s_min_app_energy_level_perc() const;
  public:
  void clear_ap_s_min_app_energy_level_perc();
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_min_app_energy_level_perc() const;
  void set_ap_s_min_app_energy_level_perc(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ap_s_min_app_energy_level_perc() const;
  void _internal_set_ap_s_min_app_energy_level_perc(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional float AP_S_CONFIRMATION_TIME_S = 2962;
  bool has_ap_s_confirmation_time_s() const;
  private:
  bool _internal_has_ap_s_confirmation_time_s() const;
  public:
  void clear_ap_s_confirmation_time_s();
  float ap_s_confirmation_time_s() const;
  void set_ap_s_confirmation_time_s(float value);
  private:
  float _internal_ap_s_confirmation_time_s() const;
  void _internal_set_ap_s_confirmation_time_s(float value);
  public:

  // optional float AP_S_BRAKE_PERSS_THRESH_P_BAR = 3118;
  bool has_ap_s_brake_perss_thresh_p_bar() const;
  private:
  bool _internal_has_ap_s_brake_perss_thresh_p_bar() const;
  public:
  void clear_ap_s_brake_perss_thresh_p_bar();
  float ap_s_brake_perss_thresh_p_bar() const;
  void set_ap_s_brake_perss_thresh_p_bar(float value);
  private:
  float _internal_ap_s_brake_perss_thresh_p_bar() const;
  void _internal_set_ap_s_brake_perss_thresh_p_bar(float value);
  public:

  // optional uint32 AP_S_REM_FINGER_MOVE_DELAY_US = 3434;
  bool has_ap_s_rem_finger_move_delay_us() const;
  private:
  bool _internal_has_ap_s_rem_finger_move_delay_us() const;
  public:
  void clear_ap_s_rem_finger_move_delay_us();
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_rem_finger_move_delay_us() const;
  void set_ap_s_rem_finger_move_delay_us(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ap_s_rem_finger_move_delay_us() const;
  void _internal_set_ap_s_rem_finger_move_delay_us(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 AP_S_REM_FINGER_MOV_THRESH_PX = 3512;
  bool has_ap_s_rem_finger_mov_thresh_px() const;
  private:
  bool _internal_has_ap_s_rem_finger_mov_thresh_px() const;
  public:
  void clear_ap_s_rem_finger_mov_thresh_px();
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_rem_finger_mov_thresh_px() const;
  void set_ap_s_rem_finger_mov_thresh_px(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ap_s_rem_finger_mov_thresh_px() const;
  void _internal_set_ap_s_rem_finger_mov_thresh_px(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 AP_S_APP_RES_X_NU = 3584;
  bool has_ap_s_app_res_x_nu() const;
  private:
  bool _internal_has_ap_s_app_res_x_nu() const;
  public:
  void clear_ap_s_app_res_x_nu();
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_app_res_x_nu() const;
  void set_ap_s_app_res_x_nu(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ap_s_app_res_x_nu() const;
  void _internal_set_ap_s_app_res_x_nu(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional float AP_S_STEERING_TORQUE_THRESH_NM = 3601;
  bool has_ap_s_steering_torque_thresh_nm() const;
  private:
  bool _internal_has_ap_s_steering_torque_thresh_nm() const;
  public:
  void clear_ap_s_steering_torque_thresh_nm();
  float ap_s_steering_torque_thresh_nm() const;
  void set_ap_s_steering_torque_thresh_nm(float value);
  private:
  float _internal_ap_s_steering_torque_thresh_nm() const;
  void _internal_set_ap_s_steering_torque_thresh_nm(float value);
  public:

  // optional float AP_S_DEADMANSWITCH_THRESHOLD_TIMER_S = 3822;
  bool has_ap_s_deadmanswitch_threshold_timer_s() const;
  private:
  bool _internal_has_ap_s_deadmanswitch_threshold_timer_s() const;
  public:
  void clear_ap_s_deadmanswitch_threshold_timer_s();
  float ap_s_deadmanswitch_threshold_timer_s() const;
  void set_ap_s_deadmanswitch_threshold_timer_s(float value);
  private:
  float _internal_ap_s_deadmanswitch_threshold_timer_s() const;
  void _internal_set_ap_s_deadmanswitch_threshold_timer_s(float value);
  public:

  // optional float AP_S_STOP_DIST_THRESH_M = 3902;
  bool has_ap_s_stop_dist_thresh_m() const;
  private:
  bool _internal_has_ap_s_stop_dist_thresh_m() const;
  public:
  void clear_ap_s_stop_dist_thresh_m();
  float ap_s_stop_dist_thresh_m() const;
  void set_ap_s_stop_dist_thresh_m(float value);
  private:
  float _internal_ap_s_stop_dist_thresh_m() const;
  void _internal_set_ap_s_stop_dist_thresh_m(float value);
  public:

  // @@protoc_insertion_point(class_scope:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::pb::eco::signal_header::SignalHeader* ssigheader_;
  ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* sysfuncparams_;
  float ap_s_overshoot_dist_thresh_m_;
  float ap_s_undershoot_dist_thresh_m_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_num_ignored_rem_alive_nu_;
  bool ap_s_check_pdc_system_state_nu_;
  bool ap_s_do_not_check_rem_key_nu_;
  float ap_s_reset_map_dist_m_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_num_ignored_key_alive_nu_;
  float ap_s_brake_perss_thresh_c_bar_;
  ::PROTOBUF_NAMESPACE_ID::uint32 uiversionnumber_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_app_res_y_nu_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_min_app_energy_level_perc_;
  float ap_s_confirmation_time_s_;
  float ap_s_brake_perss_thresh_p_bar_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_rem_finger_move_delay_us_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_rem_finger_mov_thresh_px_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ap_s_app_res_x_nu_;
  float ap_s_steering_torque_thresh_nm_;
  float ap_s_deadmanswitch_threshold_timer_s_;
  float ap_s_stop_dist_thresh_m_;
  friend struct ::TableStruct_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto;
};
// -------------------------------------------------------------------

class FC_PARKSM_Params_array_port :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params_array_port) */ {
 public:
  FC_PARKSM_Params_array_port();
  virtual ~FC_PARKSM_Params_array_port();

  FC_PARKSM_Params_array_port(const FC_PARKSM_Params_array_port& from);
  FC_PARKSM_Params_array_port(FC_PARKSM_Params_array_port&& from) noexcept
    : FC_PARKSM_Params_array_port() {
    *this = ::std::move(from);
  }

  inline FC_PARKSM_Params_array_port& operator=(const FC_PARKSM_Params_array_port& from) {
    CopyFrom(from);
    return *this;
  }
  inline FC_PARKSM_Params_array_port& operator=(FC_PARKSM_Params_array_port&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FC_PARKSM_Params_array_port& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FC_PARKSM_Params_array_port* internal_default_instance() {
    return reinterpret_cast<const FC_PARKSM_Params_array_port*>(
               &_FC_PARKSM_Params_array_port_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FC_PARKSM_Params_array_port& a, FC_PARKSM_Params_array_port& b) {
    a.Swap(&b);
  }
  inline void Swap(FC_PARKSM_Params_array_port* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FC_PARKSM_Params_array_port* New() const final {
    return CreateMaybeMessage<FC_PARKSM_Params_array_port>(nullptr);
  }

  FC_PARKSM_Params_array_port* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FC_PARKSM_Params_array_port>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FC_PARKSM_Params_array_port& from);
  void MergeFrom(const FC_PARKSM_Params_array_port& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FC_PARKSM_Params_array_port* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params_array_port";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto);
    return ::descriptor_table_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2868,
  };
  // repeated .pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params data = 2868;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params >*
      mutable_data();
  private:
  const ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params& _internal_data(int index) const;
  ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params* _internal_add_data();
  public:
  const ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params& data(int index) const;
  ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params >&
      data() const;

  // @@protoc_insertion_point(class_scope:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params_array_port)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params > data_;
  friend struct ::TableStruct_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FC_PARKSM_Params

// optional uint32 uiVersionNumber = 2124;
inline bool FC_PARKSM_Params::_internal_has_uiversionnumber() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_uiversionnumber() const {
  return _internal_has_uiversionnumber();
}
inline void FC_PARKSM_Params::clear_uiversionnumber() {
  uiversionnumber_ = 0u;
  _has_bits_[0] &= ~0x00000400u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::_internal_uiversionnumber() const {
  return uiversionnumber_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::uiversionnumber() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.uiVersionNumber)
  return _internal_uiversionnumber();
}
inline void FC_PARKSM_Params::_internal_set_uiversionnumber(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000400u;
  uiversionnumber_ = value;
}
inline void FC_PARKSM_Params::set_uiversionnumber(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_uiversionnumber(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.uiVersionNumber)
}

// optional .pb.eco.signal_header.SignalHeader sSigHeader = 1033;
inline bool FC_PARKSM_Params::_internal_has_ssigheader() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || ssigheader_ != nullptr);
  return value;
}
inline bool FC_PARKSM_Params::has_ssigheader() const {
  return _internal_has_ssigheader();
}
inline const ::pb::eco::signal_header::SignalHeader& FC_PARKSM_Params::_internal_ssigheader() const {
  const ::pb::eco::signal_header::SignalHeader* p = ssigheader_;
  return p != nullptr ? *p : *reinterpret_cast<const ::pb::eco::signal_header::SignalHeader*>(
      &::pb::eco::signal_header::_SignalHeader_default_instance_);
}
inline const ::pb::eco::signal_header::SignalHeader& FC_PARKSM_Params::ssigheader() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.sSigHeader)
  return _internal_ssigheader();
}
inline ::pb::eco::signal_header::SignalHeader* FC_PARKSM_Params::release_ssigheader() {
  // @@protoc_insertion_point(field_release:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.sSigHeader)
  _has_bits_[0] &= ~0x00000001u;
  ::pb::eco::signal_header::SignalHeader* temp = ssigheader_;
  ssigheader_ = nullptr;
  return temp;
}
inline ::pb::eco::signal_header::SignalHeader* FC_PARKSM_Params::_internal_mutable_ssigheader() {
  _has_bits_[0] |= 0x00000001u;
  if (ssigheader_ == nullptr) {
    auto* p = CreateMaybeMessage<::pb::eco::signal_header::SignalHeader>(GetArenaNoVirtual());
    ssigheader_ = p;
  }
  return ssigheader_;
}
inline ::pb::eco::signal_header::SignalHeader* FC_PARKSM_Params::mutable_ssigheader() {
  // @@protoc_insertion_point(field_mutable:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.sSigHeader)
  return _internal_mutable_ssigheader();
}
inline void FC_PARKSM_Params::set_allocated_ssigheader(::pb::eco::signal_header::SignalHeader* ssigheader) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(ssigheader_);
  }
  if (ssigheader) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      ssigheader = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ssigheader, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  ssigheader_ = ssigheader;
  // @@protoc_insertion_point(field_set_allocated:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.sSigHeader)
}

// optional float AP_S_BRAKE_PERSS_THRESH_P_BAR = 3118;
inline bool FC_PARKSM_Params::_internal_has_ap_s_brake_perss_thresh_p_bar() const {
  bool value = (_has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_brake_perss_thresh_p_bar() const {
  return _internal_has_ap_s_brake_perss_thresh_p_bar();
}
inline void FC_PARKSM_Params::clear_ap_s_brake_perss_thresh_p_bar() {
  ap_s_brake_perss_thresh_p_bar_ = 0;
  _has_bits_[0] &= ~0x00004000u;
}
inline float FC_PARKSM_Params::_internal_ap_s_brake_perss_thresh_p_bar() const {
  return ap_s_brake_perss_thresh_p_bar_;
}
inline float FC_PARKSM_Params::ap_s_brake_perss_thresh_p_bar() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_BRAKE_PERSS_THRESH_P_BAR)
  return _internal_ap_s_brake_perss_thresh_p_bar();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_brake_perss_thresh_p_bar(float value) {
  _has_bits_[0] |= 0x00004000u;
  ap_s_brake_perss_thresh_p_bar_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_brake_perss_thresh_p_bar(float value) {
  _internal_set_ap_s_brake_perss_thresh_p_bar(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_BRAKE_PERSS_THRESH_P_BAR)
}

// optional float AP_S_BRAKE_PERSS_THRESH_C_BAR = 1702;
inline bool FC_PARKSM_Params::_internal_has_ap_s_brake_perss_thresh_c_bar() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_brake_perss_thresh_c_bar() const {
  return _internal_has_ap_s_brake_perss_thresh_c_bar();
}
inline void FC_PARKSM_Params::clear_ap_s_brake_perss_thresh_c_bar() {
  ap_s_brake_perss_thresh_c_bar_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline float FC_PARKSM_Params::_internal_ap_s_brake_perss_thresh_c_bar() const {
  return ap_s_brake_perss_thresh_c_bar_;
}
inline float FC_PARKSM_Params::ap_s_brake_perss_thresh_c_bar() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_BRAKE_PERSS_THRESH_C_BAR)
  return _internal_ap_s_brake_perss_thresh_c_bar();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_brake_perss_thresh_c_bar(float value) {
  _has_bits_[0] |= 0x00000200u;
  ap_s_brake_perss_thresh_c_bar_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_brake_perss_thresh_c_bar(float value) {
  _internal_set_ap_s_brake_perss_thresh_c_bar(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_BRAKE_PERSS_THRESH_C_BAR)
}

// optional float AP_S_CONFIRMATION_TIME_S = 2962;
inline bool FC_PARKSM_Params::_internal_has_ap_s_confirmation_time_s() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_confirmation_time_s() const {
  return _internal_has_ap_s_confirmation_time_s();
}
inline void FC_PARKSM_Params::clear_ap_s_confirmation_time_s() {
  ap_s_confirmation_time_s_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline float FC_PARKSM_Params::_internal_ap_s_confirmation_time_s() const {
  return ap_s_confirmation_time_s_;
}
inline float FC_PARKSM_Params::ap_s_confirmation_time_s() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_CONFIRMATION_TIME_S)
  return _internal_ap_s_confirmation_time_s();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_confirmation_time_s(float value) {
  _has_bits_[0] |= 0x00002000u;
  ap_s_confirmation_time_s_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_confirmation_time_s(float value) {
  _internal_set_ap_s_confirmation_time_s(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_CONFIRMATION_TIME_S)
}

// optional float AP_S_DEADMANSWITCH_THRESHOLD_TIMER_S = 3822;
inline bool FC_PARKSM_Params::_internal_has_ap_s_deadmanswitch_threshold_timer_s() const {
  bool value = (_has_bits_[0] & 0x00080000u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_deadmanswitch_threshold_timer_s() const {
  return _internal_has_ap_s_deadmanswitch_threshold_timer_s();
}
inline void FC_PARKSM_Params::clear_ap_s_deadmanswitch_threshold_timer_s() {
  ap_s_deadmanswitch_threshold_timer_s_ = 0;
  _has_bits_[0] &= ~0x00080000u;
}
inline float FC_PARKSM_Params::_internal_ap_s_deadmanswitch_threshold_timer_s() const {
  return ap_s_deadmanswitch_threshold_timer_s_;
}
inline float FC_PARKSM_Params::ap_s_deadmanswitch_threshold_timer_s() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_DEADMANSWITCH_THRESHOLD_TIMER_S)
  return _internal_ap_s_deadmanswitch_threshold_timer_s();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_deadmanswitch_threshold_timer_s(float value) {
  _has_bits_[0] |= 0x00080000u;
  ap_s_deadmanswitch_threshold_timer_s_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_deadmanswitch_threshold_timer_s(float value) {
  _internal_set_ap_s_deadmanswitch_threshold_timer_s(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_DEADMANSWITCH_THRESHOLD_TIMER_S)
}

// optional float AP_S_STEERING_TORQUE_THRESH_NM = 3601;
inline bool FC_PARKSM_Params::_internal_has_ap_s_steering_torque_thresh_nm() const {
  bool value = (_has_bits_[0] & 0x00040000u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_steering_torque_thresh_nm() const {
  return _internal_has_ap_s_steering_torque_thresh_nm();
}
inline void FC_PARKSM_Params::clear_ap_s_steering_torque_thresh_nm() {
  ap_s_steering_torque_thresh_nm_ = 0;
  _has_bits_[0] &= ~0x00040000u;
}
inline float FC_PARKSM_Params::_internal_ap_s_steering_torque_thresh_nm() const {
  return ap_s_steering_torque_thresh_nm_;
}
inline float FC_PARKSM_Params::ap_s_steering_torque_thresh_nm() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_STEERING_TORQUE_THRESH_NM)
  return _internal_ap_s_steering_torque_thresh_nm();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_steering_torque_thresh_nm(float value) {
  _has_bits_[0] |= 0x00040000u;
  ap_s_steering_torque_thresh_nm_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_steering_torque_thresh_nm(float value) {
  _internal_set_ap_s_steering_torque_thresh_nm(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_STEERING_TORQUE_THRESH_NM)
}

// optional uint32 AP_S_REM_FINGER_MOV_THRESH_PX = 3512;
inline bool FC_PARKSM_Params::_internal_has_ap_s_rem_finger_mov_thresh_px() const {
  bool value = (_has_bits_[0] & 0x00010000u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_rem_finger_mov_thresh_px() const {
  return _internal_has_ap_s_rem_finger_mov_thresh_px();
}
inline void FC_PARKSM_Params::clear_ap_s_rem_finger_mov_thresh_px() {
  ap_s_rem_finger_mov_thresh_px_ = 0u;
  _has_bits_[0] &= ~0x00010000u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::_internal_ap_s_rem_finger_mov_thresh_px() const {
  return ap_s_rem_finger_mov_thresh_px_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::ap_s_rem_finger_mov_thresh_px() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_REM_FINGER_MOV_THRESH_PX)
  return _internal_ap_s_rem_finger_mov_thresh_px();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_rem_finger_mov_thresh_px(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00010000u;
  ap_s_rem_finger_mov_thresh_px_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_rem_finger_mov_thresh_px(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ap_s_rem_finger_mov_thresh_px(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_REM_FINGER_MOV_THRESH_PX)
}

// optional uint32 AP_S_REM_FINGER_MOVE_DELAY_US = 3434;
inline bool FC_PARKSM_Params::_internal_has_ap_s_rem_finger_move_delay_us() const {
  bool value = (_has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_rem_finger_move_delay_us() const {
  return _internal_has_ap_s_rem_finger_move_delay_us();
}
inline void FC_PARKSM_Params::clear_ap_s_rem_finger_move_delay_us() {
  ap_s_rem_finger_move_delay_us_ = 0u;
  _has_bits_[0] &= ~0x00008000u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::_internal_ap_s_rem_finger_move_delay_us() const {
  return ap_s_rem_finger_move_delay_us_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::ap_s_rem_finger_move_delay_us() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_REM_FINGER_MOVE_DELAY_US)
  return _internal_ap_s_rem_finger_move_delay_us();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_rem_finger_move_delay_us(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00008000u;
  ap_s_rem_finger_move_delay_us_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_rem_finger_move_delay_us(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ap_s_rem_finger_move_delay_us(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_REM_FINGER_MOVE_DELAY_US)
}

// optional float AP_S_RESET_MAP_DIST_M = 1506;
inline bool FC_PARKSM_Params::_internal_has_ap_s_reset_map_dist_m() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_reset_map_dist_m() const {
  return _internal_has_ap_s_reset_map_dist_m();
}
inline void FC_PARKSM_Params::clear_ap_s_reset_map_dist_m() {
  ap_s_reset_map_dist_m_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline float FC_PARKSM_Params::_internal_ap_s_reset_map_dist_m() const {
  return ap_s_reset_map_dist_m_;
}
inline float FC_PARKSM_Params::ap_s_reset_map_dist_m() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_RESET_MAP_DIST_M)
  return _internal_ap_s_reset_map_dist_m();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_reset_map_dist_m(float value) {
  _has_bits_[0] |= 0x00000080u;
  ap_s_reset_map_dist_m_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_reset_map_dist_m(float value) {
  _internal_set_ap_s_reset_map_dist_m(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_RESET_MAP_DIST_M)
}

// optional float AP_S_STOP_DIST_THRESH_M = 3902;
inline bool FC_PARKSM_Params::_internal_has_ap_s_stop_dist_thresh_m() const {
  bool value = (_has_bits_[0] & 0x00100000u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_stop_dist_thresh_m() const {
  return _internal_has_ap_s_stop_dist_thresh_m();
}
inline void FC_PARKSM_Params::clear_ap_s_stop_dist_thresh_m() {
  ap_s_stop_dist_thresh_m_ = 0;
  _has_bits_[0] &= ~0x00100000u;
}
inline float FC_PARKSM_Params::_internal_ap_s_stop_dist_thresh_m() const {
  return ap_s_stop_dist_thresh_m_;
}
inline float FC_PARKSM_Params::ap_s_stop_dist_thresh_m() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_STOP_DIST_THRESH_M)
  return _internal_ap_s_stop_dist_thresh_m();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_stop_dist_thresh_m(float value) {
  _has_bits_[0] |= 0x00100000u;
  ap_s_stop_dist_thresh_m_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_stop_dist_thresh_m(float value) {
  _internal_set_ap_s_stop_dist_thresh_m(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_STOP_DIST_THRESH_M)
}

// optional float AP_S_UNDERSHOOT_DIST_THRESH_M = 807;
inline bool FC_PARKSM_Params::_internal_has_ap_s_undershoot_dist_thresh_m() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_undershoot_dist_thresh_m() const {
  return _internal_has_ap_s_undershoot_dist_thresh_m();
}
inline void FC_PARKSM_Params::clear_ap_s_undershoot_dist_thresh_m() {
  ap_s_undershoot_dist_thresh_m_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline float FC_PARKSM_Params::_internal_ap_s_undershoot_dist_thresh_m() const {
  return ap_s_undershoot_dist_thresh_m_;
}
inline float FC_PARKSM_Params::ap_s_undershoot_dist_thresh_m() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_UNDERSHOOT_DIST_THRESH_M)
  return _internal_ap_s_undershoot_dist_thresh_m();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_undershoot_dist_thresh_m(float value) {
  _has_bits_[0] |= 0x00000008u;
  ap_s_undershoot_dist_thresh_m_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_undershoot_dist_thresh_m(float value) {
  _internal_set_ap_s_undershoot_dist_thresh_m(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_UNDERSHOOT_DIST_THRESH_M)
}

// optional float AP_S_OVERSHOOT_DIST_THRESH_M = 311;
inline bool FC_PARKSM_Params::_internal_has_ap_s_overshoot_dist_thresh_m() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_overshoot_dist_thresh_m() const {
  return _internal_has_ap_s_overshoot_dist_thresh_m();
}
inline void FC_PARKSM_Params::clear_ap_s_overshoot_dist_thresh_m() {
  ap_s_overshoot_dist_thresh_m_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline float FC_PARKSM_Params::_internal_ap_s_overshoot_dist_thresh_m() const {
  return ap_s_overshoot_dist_thresh_m_;
}
inline float FC_PARKSM_Params::ap_s_overshoot_dist_thresh_m() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_OVERSHOOT_DIST_THRESH_M)
  return _internal_ap_s_overshoot_dist_thresh_m();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_overshoot_dist_thresh_m(float value) {
  _has_bits_[0] |= 0x00000004u;
  ap_s_overshoot_dist_thresh_m_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_overshoot_dist_thresh_m(float value) {
  _internal_set_ap_s_overshoot_dist_thresh_m(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_OVERSHOOT_DIST_THRESH_M)
}

// optional uint32 AP_S_NUM_IGNORED_REM_ALIVE_NU = 963;
inline bool FC_PARKSM_Params::_internal_has_ap_s_num_ignored_rem_alive_nu() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_num_ignored_rem_alive_nu() const {
  return _internal_has_ap_s_num_ignored_rem_alive_nu();
}
inline void FC_PARKSM_Params::clear_ap_s_num_ignored_rem_alive_nu() {
  ap_s_num_ignored_rem_alive_nu_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::_internal_ap_s_num_ignored_rem_alive_nu() const {
  return ap_s_num_ignored_rem_alive_nu_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::ap_s_num_ignored_rem_alive_nu() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_NUM_IGNORED_REM_ALIVE_NU)
  return _internal_ap_s_num_ignored_rem_alive_nu();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_num_ignored_rem_alive_nu(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  ap_s_num_ignored_rem_alive_nu_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_num_ignored_rem_alive_nu(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ap_s_num_ignored_rem_alive_nu(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_NUM_IGNORED_REM_ALIVE_NU)
}

// optional uint32 AP_S_APP_RES_X_NU = 3584;
inline bool FC_PARKSM_Params::_internal_has_ap_s_app_res_x_nu() const {
  bool value = (_has_bits_[0] & 0x00020000u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_app_res_x_nu() const {
  return _internal_has_ap_s_app_res_x_nu();
}
inline void FC_PARKSM_Params::clear_ap_s_app_res_x_nu() {
  ap_s_app_res_x_nu_ = 0u;
  _has_bits_[0] &= ~0x00020000u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::_internal_ap_s_app_res_x_nu() const {
  return ap_s_app_res_x_nu_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::ap_s_app_res_x_nu() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_APP_RES_X_NU)
  return _internal_ap_s_app_res_x_nu();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_app_res_x_nu(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00020000u;
  ap_s_app_res_x_nu_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_app_res_x_nu(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ap_s_app_res_x_nu(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_APP_RES_X_NU)
}

// optional uint32 AP_S_APP_RES_Y_NU = 2228;
inline bool FC_PARKSM_Params::_internal_has_ap_s_app_res_y_nu() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_app_res_y_nu() const {
  return _internal_has_ap_s_app_res_y_nu();
}
inline void FC_PARKSM_Params::clear_ap_s_app_res_y_nu() {
  ap_s_app_res_y_nu_ = 0u;
  _has_bits_[0] &= ~0x00000800u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::_internal_ap_s_app_res_y_nu() const {
  return ap_s_app_res_y_nu_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::ap_s_app_res_y_nu() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_APP_RES_Y_NU)
  return _internal_ap_s_app_res_y_nu();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_app_res_y_nu(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000800u;
  ap_s_app_res_y_nu_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_app_res_y_nu(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ap_s_app_res_y_nu(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_APP_RES_Y_NU)
}

// optional bool AP_S_CHECK_PDC_SYSTEM_STATE_NU = 2177;
inline bool FC_PARKSM_Params::_internal_has_ap_s_check_pdc_system_state_nu() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_check_pdc_system_state_nu() const {
  return _internal_has_ap_s_check_pdc_system_state_nu();
}
inline void FC_PARKSM_Params::clear_ap_s_check_pdc_system_state_nu() {
  ap_s_check_pdc_system_state_nu_ = false;
  _has_bits_[0] &= ~0x00000020u;
}
inline bool FC_PARKSM_Params::_internal_ap_s_check_pdc_system_state_nu() const {
  return ap_s_check_pdc_system_state_nu_;
}
inline bool FC_PARKSM_Params::ap_s_check_pdc_system_state_nu() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_CHECK_PDC_SYSTEM_STATE_NU)
  return _internal_ap_s_check_pdc_system_state_nu();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_check_pdc_system_state_nu(bool value) {
  _has_bits_[0] |= 0x00000020u;
  ap_s_check_pdc_system_state_nu_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_check_pdc_system_state_nu(bool value) {
  _internal_set_ap_s_check_pdc_system_state_nu(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_CHECK_PDC_SYSTEM_STATE_NU)
}

// optional uint32 AP_S_NUM_IGNORED_KEY_ALIVE_NU = 1517;
inline bool FC_PARKSM_Params::_internal_has_ap_s_num_ignored_key_alive_nu() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_num_ignored_key_alive_nu() const {
  return _internal_has_ap_s_num_ignored_key_alive_nu();
}
inline void FC_PARKSM_Params::clear_ap_s_num_ignored_key_alive_nu() {
  ap_s_num_ignored_key_alive_nu_ = 0u;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::_internal_ap_s_num_ignored_key_alive_nu() const {
  return ap_s_num_ignored_key_alive_nu_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::ap_s_num_ignored_key_alive_nu() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_NUM_IGNORED_KEY_ALIVE_NU)
  return _internal_ap_s_num_ignored_key_alive_nu();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_num_ignored_key_alive_nu(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000100u;
  ap_s_num_ignored_key_alive_nu_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_num_ignored_key_alive_nu(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ap_s_num_ignored_key_alive_nu(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_NUM_IGNORED_KEY_ALIVE_NU)
}

// optional uint32 AP_S_MIN_APP_ENERGY_LEVEL_PERC = 2647;
inline bool FC_PARKSM_Params::_internal_has_ap_s_min_app_energy_level_perc() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_min_app_energy_level_perc() const {
  return _internal_has_ap_s_min_app_energy_level_perc();
}
inline void FC_PARKSM_Params::clear_ap_s_min_app_energy_level_perc() {
  ap_s_min_app_energy_level_perc_ = 0u;
  _has_bits_[0] &= ~0x00001000u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::_internal_ap_s_min_app_energy_level_perc() const {
  return ap_s_min_app_energy_level_perc_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 FC_PARKSM_Params::ap_s_min_app_energy_level_perc() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_MIN_APP_ENERGY_LEVEL_PERC)
  return _internal_ap_s_min_app_energy_level_perc();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_min_app_energy_level_perc(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00001000u;
  ap_s_min_app_energy_level_perc_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_min_app_energy_level_perc(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ap_s_min_app_energy_level_perc(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_MIN_APP_ENERGY_LEVEL_PERC)
}

// optional bool AP_S_DO_NOT_CHECK_REM_KEY_NU = 555;
inline bool FC_PARKSM_Params::_internal_has_ap_s_do_not_check_rem_key_nu() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool FC_PARKSM_Params::has_ap_s_do_not_check_rem_key_nu() const {
  return _internal_has_ap_s_do_not_check_rem_key_nu();
}
inline void FC_PARKSM_Params::clear_ap_s_do_not_check_rem_key_nu() {
  ap_s_do_not_check_rem_key_nu_ = false;
  _has_bits_[0] &= ~0x00000040u;
}
inline bool FC_PARKSM_Params::_internal_ap_s_do_not_check_rem_key_nu() const {
  return ap_s_do_not_check_rem_key_nu_;
}
inline bool FC_PARKSM_Params::ap_s_do_not_check_rem_key_nu() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_DO_NOT_CHECK_REM_KEY_NU)
  return _internal_ap_s_do_not_check_rem_key_nu();
}
inline void FC_PARKSM_Params::_internal_set_ap_s_do_not_check_rem_key_nu(bool value) {
  _has_bits_[0] |= 0x00000040u;
  ap_s_do_not_check_rem_key_nu_ = value;
}
inline void FC_PARKSM_Params::set_ap_s_do_not_check_rem_key_nu(bool value) {
  _internal_set_ap_s_do_not_check_rem_key_nu(value);
  // @@protoc_insertion_point(field_set:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.AP_S_DO_NOT_CHECK_REM_KEY_NU)
}

// optional .pb.ap_common.fc_parksm_sys_func_params.FC_PARKSM_Sys_Func_Params sysFuncParams = 3021;
inline bool FC_PARKSM_Params::_internal_has_sysfuncparams() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || sysfuncparams_ != nullptr);
  return value;
}
inline bool FC_PARKSM_Params::has_sysfuncparams() const {
  return _internal_has_sysfuncparams();
}
inline const ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params& FC_PARKSM_Params::_internal_sysfuncparams() const {
  const ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* p = sysfuncparams_;
  return p != nullptr ? *p : *reinterpret_cast<const ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params*>(
      &::pb::ap_common::fc_parksm_sys_func_params::_FC_PARKSM_Sys_Func_Params_default_instance_);
}
inline const ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params& FC_PARKSM_Params::sysfuncparams() const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.sysFuncParams)
  return _internal_sysfuncparams();
}
inline ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* FC_PARKSM_Params::release_sysfuncparams() {
  // @@protoc_insertion_point(field_release:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.sysFuncParams)
  _has_bits_[0] &= ~0x00000002u;
  ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* temp = sysfuncparams_;
  sysfuncparams_ = nullptr;
  return temp;
}
inline ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* FC_PARKSM_Params::_internal_mutable_sysfuncparams() {
  _has_bits_[0] |= 0x00000002u;
  if (sysfuncparams_ == nullptr) {
    auto* p = CreateMaybeMessage<::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params>(GetArenaNoVirtual());
    sysfuncparams_ = p;
  }
  return sysfuncparams_;
}
inline ::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* FC_PARKSM_Params::mutable_sysfuncparams() {
  // @@protoc_insertion_point(field_mutable:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.sysFuncParams)
  return _internal_mutable_sysfuncparams();
}
inline void FC_PARKSM_Params::set_allocated_sysfuncparams(::pb::ap_common::fc_parksm_sys_func_params::FC_PARKSM_Sys_Func_Params* sysfuncparams) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(sysfuncparams_);
  }
  if (sysfuncparams) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      sysfuncparams = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sysfuncparams, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  sysfuncparams_ = sysfuncparams;
  // @@protoc_insertion_point(field_set_allocated:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params.sysFuncParams)
}

// -------------------------------------------------------------------

// FC_PARKSM_Params_array_port

// repeated .pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params data = 2868;
inline int FC_PARKSM_Params_array_port::_internal_data_size() const {
  return data_.size();
}
inline int FC_PARKSM_Params_array_port::data_size() const {
  return _internal_data_size();
}
inline void FC_PARKSM_Params_array_port::clear_data() {
  data_.Clear();
}
inline ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params* FC_PARKSM_Params_array_port::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params_array_port.data)
  return data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params >*
FC_PARKSM_Params_array_port::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params_array_port.data)
  return &data_;
}
inline const ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params& FC_PARKSM_Params_array_port::_internal_data(int index) const {
  return data_.Get(index);
}
inline const ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params& FC_PARKSM_Params_array_port::data(int index) const {
  // @@protoc_insertion_point(field_get:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params_array_port.data)
  return _internal_data(index);
}
inline ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params* FC_PARKSM_Params_array_port::_internal_add_data() {
  return data_.Add();
}
inline ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params* FC_PARKSM_Params_array_port::add_data() {
  // @@protoc_insertion_point(field_add:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params_array_port.data)
  return _internal_add_data();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::ap_psm_app::fc_parksm_params::FC_PARKSM_Params >&
FC_PARKSM_Params_array_port::data() const {
  // @@protoc_insertion_point(field_list:pb.ap_psm_app.fc_parksm_params.FC_PARKSM_Params_array_port.data)
  return data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fc_parksm_params
}  // namespace ap_psm_app
}  // namespace pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ap_5fpsm_5fapp_2ffc_5fparksm_5fparams_2eproto
