// Attention, this file is generated by Cobolt from template: D:\.bbs_conan\c029a0\1\codegen\templates\types_14\enum.h.template!

#ifdef ECO_C_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C and C++14 types mixed
  #endif
#endif
#ifdef ECO_CPP_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C++ and C++14 types mixed
  #endif
#endif
#define ECO_CPP14_TYPES_USED

#ifndef MF_MEMPARK_SYSTEM_DEFINED_POSE_TYPE_H_
#define MF_MEMPARK_SYSTEM_DEFINED_POSE_TYPE_H_

#include "Platform_Types.h"

namespace mf_mempark
{
  ///Pose type of the target pose provided by the system
  enum class SystemDefinedPoseType : uint8
  {
      SYSTEM_DEF_TYPE_CURRENT_EGO = 0U,
      SYSTEM_DEF_TYPE_PAR = 1U,
      SYSTEM_DEF_TYPE_PERP_BWD = 2U,
      SYSTEM_DEF_TYPE_PERP_FWD = 3U,
      SYSTEM_DEF_TYPE_FOLLOW_BWD = 4U,
      SYSTEM_DEF_TYPE_FOLLOW_FWD = 5U,
      SYSTEM_DEF_TYPE_ANGLE_BWD = 6U,
      MAX_NUM_SYSTEM_DEF_POSE_TYPES = 7U,
  };
} // namespace mf_mempark
#endif // MF_MEMPARK_SYSTEM_DEFINED_POSE_TYPE_H_
