// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mf_drvwarnsm_core/drv_warn_core_status_port.proto

#include "mf_drvwarnsm_core/drv_warn_core_status_port.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_eco_2fsignal_5fheader_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SignalHeader_eco_2fsignal_5fheader_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_DrvWarnCoreStatusPort_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto;
namespace pb {
namespace mf_drvwarnsm_core {
namespace drv_warn_core_status_port {
class DrvWarnCoreStatusPortDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DrvWarnCoreStatusPort> _instance;
} _DrvWarnCoreStatusPort_default_instance_;
class DrvWarnCoreStatusPort_array_portDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DrvWarnCoreStatusPort_array_port> _instance;
} _DrvWarnCoreStatusPort_array_port_default_instance_;
}  // namespace drv_warn_core_status_port
}  // namespace mf_drvwarnsm_core
}  // namespace pb
static void InitDefaultsscc_info_DrvWarnCoreStatusPort_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pb::mf_drvwarnsm_core::drv_warn_core_status_port::_DrvWarnCoreStatusPort_default_instance_;
    new (ptr) ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_DrvWarnCoreStatusPort_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_DrvWarnCoreStatusPort_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto}, {
      &scc_info_SignalHeader_eco_2fsignal_5fheader_2eproto.base,}};

static void InitDefaultsscc_info_DrvWarnCoreStatusPort_array_port_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pb::mf_drvwarnsm_core::drv_warn_core_status_port::_DrvWarnCoreStatusPort_array_port_default_instance_;
    new (ptr) ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort_array_port();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort_array_port::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_DrvWarnCoreStatusPort_array_port_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_DrvWarnCoreStatusPort_array_port_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto}, {
      &scc_info_DrvWarnCoreStatusPort_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort, uiversionnumber_),
  PROTOBUF_FIELD_OFFSET(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort, ssigheader_),
  PROTOBUF_FIELD_OFFSET(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort, pdwactivestate_nu_),
  PROTOBUF_FIELD_OFFSET(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort, pdwcorestate_nu_),
  PROTOBUF_FIELD_OFFSET(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort, whpcorestate_nu_),
  2,
  0,
  1,
  3,
  4,
  PROTOBUF_FIELD_OFFSET(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort_array_port, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort_array_port, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort_array_port, data_),
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, sizeof(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort)},
  { 15, 21, sizeof(::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort_array_port)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::pb::mf_drvwarnsm_core::drv_warn_core_status_port::_DrvWarnCoreStatusPort_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::pb::mf_drvwarnsm_core::drv_warn_core_status_port::_DrvWarnCoreStatusPort_array_port_default_instance_),
};

const char descriptor_table_protodef_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n1mf_drvwarnsm_core/drv_warn_core_status"
  "_port.proto\022.pb.mf_drvwarnsm_core.drv_wa"
  "rn_core_status_port\032\027eco/signal_header.p"
  "roto\032%mf_drvwarnsm_core/dwfcore_state.pr"
  "oto\"\236\002\n\025DrvWarnCoreStatusPort\022\030\n\017uiVersi"
  "onNumber\030\314\020 \001(\r\0227\n\nsSigHeader\030\211\010 \001(\0132\".p"
  "b.eco.signal_header.SignalHeader\022\032\n\021pdwA"
  "ctiveState_nu\030\377\002 \001(\010\022J\n\017pdwCoreState_nu\030"
  "\333\024 \001(\01620.pb.mf_drvwarnsm_core.dwfcore_st"
  "ate.DWFCoreState\022J\n\017whpCoreState_nu\030\212\034 \001"
  "(\01620.pb.mf_drvwarnsm_core.dwfcore_state."
  "DWFCoreState\"x\n DrvWarnCoreStatusPort_ar"
  "ray_port\022T\n\004data\030\253\032 \003(\0132E.pb.mf_drvwarns"
  "m_core.drv_warn_core_status_port.DrvWarn"
  "CoreStatusPort"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto_deps[2] = {
  &::descriptor_table_eco_2fsignal_5fheader_2eproto,
  &::descriptor_table_mf_5fdrvwarnsm_5fcore_2fdwfcore_5fstate_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto_sccs[2] = {
  &scc_info_DrvWarnCoreStatusPort_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto.base,
  &scc_info_DrvWarnCoreStatusPort_array_port_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto_once;
static bool descriptor_table_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto = {
  &descriptor_table_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto_initialized, descriptor_table_protodef_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto, "mf_drvwarnsm_core/drv_warn_core_status_port.proto", 574,
  &descriptor_table_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto_once, descriptor_table_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto_sccs, descriptor_table_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto_deps, 2, 2,
  schemas, file_default_instances, TableStruct_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto::offsets,
  file_level_metadata_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto, 2, file_level_enum_descriptors_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto, file_level_service_descriptors_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto), true);
namespace pb {
namespace mf_drvwarnsm_core {
namespace drv_warn_core_status_port {

// ===================================================================

void DrvWarnCoreStatusPort::InitAsDefaultInstance() {
  ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::_DrvWarnCoreStatusPort_default_instance_._instance.get_mutable()->ssigheader_ = const_cast< ::pb::eco::signal_header::SignalHeader*>(
      ::pb::eco::signal_header::SignalHeader::internal_default_instance());
}
class DrvWarnCoreStatusPort::_Internal {
 public:
  using HasBits = decltype(std::declval<DrvWarnCoreStatusPort>()._has_bits_);
  static void set_has_uiversionnumber(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::pb::eco::signal_header::SignalHeader& ssigheader(const DrvWarnCoreStatusPort* msg);
  static void set_has_ssigheader(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_pdwactivestate_nu(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_pdwcorestate_nu(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_whpcorestate_nu(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

const ::pb::eco::signal_header::SignalHeader&
DrvWarnCoreStatusPort::_Internal::ssigheader(const DrvWarnCoreStatusPort* msg) {
  return *msg->ssigheader_;
}
void DrvWarnCoreStatusPort::clear_ssigheader() {
  if (ssigheader_ != nullptr) ssigheader_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
DrvWarnCoreStatusPort::DrvWarnCoreStatusPort()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
}
DrvWarnCoreStatusPort::DrvWarnCoreStatusPort(const DrvWarnCoreStatusPort& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_ssigheader()) {
    ssigheader_ = new ::pb::eco::signal_header::SignalHeader(*from.ssigheader_);
  } else {
    ssigheader_ = nullptr;
  }
  ::memcpy(&pdwactivestate_nu_, &from.pdwactivestate_nu_,
    static_cast<size_t>(reinterpret_cast<char*>(&whpcorestate_nu_) -
    reinterpret_cast<char*>(&pdwactivestate_nu_)) + sizeof(whpcorestate_nu_));
  // @@protoc_insertion_point(copy_constructor:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
}

void DrvWarnCoreStatusPort::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DrvWarnCoreStatusPort_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto.base);
  ::memset(&ssigheader_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&whpcorestate_nu_) -
      reinterpret_cast<char*>(&ssigheader_)) + sizeof(whpcorestate_nu_));
}

DrvWarnCoreStatusPort::~DrvWarnCoreStatusPort() {
  // @@protoc_insertion_point(destructor:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
  SharedDtor();
}

void DrvWarnCoreStatusPort::SharedDtor() {
  if (this != internal_default_instance()) delete ssigheader_;
}

void DrvWarnCoreStatusPort::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DrvWarnCoreStatusPort& DrvWarnCoreStatusPort::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DrvWarnCoreStatusPort_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto.base);
  return *internal_default_instance();
}


void DrvWarnCoreStatusPort::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(ssigheader_ != nullptr);
    ssigheader_->Clear();
  }
  if (cached_has_bits & 0x0000001eu) {
    ::memset(&pdwactivestate_nu_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&whpcorestate_nu_) -
        reinterpret_cast<char*>(&pdwactivestate_nu_)) + sizeof(whpcorestate_nu_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* DrvWarnCoreStatusPort::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional bool pdwActiveState_nu = 383;
      case 383:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 248)) {
          _Internal::set_has_pdwactivestate_nu(&has_bits);
          pdwactivestate_nu_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .pb.eco.signal_header.SignalHeader sSigHeader = 1033;
      case 1033:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_ssigheader(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 uiVersionNumber = 2124;
      case 2124:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 96)) {
          _Internal::set_has_uiversionnumber(&has_bits);
          uiversionnumber_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .pb.mf_drvwarnsm_core.dwfcore_state.DWFCoreState pdwCoreState_nu = 2651;
      case 2651:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 216)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::pb::mf_drvwarnsm_core::dwfcore_state::DWFCoreState_IsValid(val))) {
            _internal_set_pdwcorestate_nu(static_cast<::pb::mf_drvwarnsm_core::dwfcore_state::DWFCoreState>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2651, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // optional .pb.mf_drvwarnsm_core.dwfcore_state.DWFCoreState whpCoreState_nu = 3594;
      case 3594:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::pb::mf_drvwarnsm_core::dwfcore_state::DWFCoreState_IsValid(val))) {
            _internal_set_whpcorestate_nu(static_cast<::pb::mf_drvwarnsm_core::dwfcore_state::DWFCoreState>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(3594, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DrvWarnCoreStatusPort::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool pdwActiveState_nu = 383;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(383, this->_internal_pdwactivestate_nu(), target);
  }

  // optional .pb.eco.signal_header.SignalHeader sSigHeader = 1033;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1033, _Internal::ssigheader(this), target, stream);
  }

  // optional uint32 uiVersionNumber = 2124;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2124, this->_internal_uiversionnumber(), target);
  }

  // optional .pb.mf_drvwarnsm_core.dwfcore_state.DWFCoreState pdwCoreState_nu = 2651;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2651, this->_internal_pdwcorestate_nu(), target);
  }

  // optional .pb.mf_drvwarnsm_core.dwfcore_state.DWFCoreState whpCoreState_nu = 3594;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3594, this->_internal_whpcorestate_nu(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
  return target;
}

size_t DrvWarnCoreStatusPort::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional .pb.eco.signal_header.SignalHeader sSigHeader = 1033;
    if (cached_has_bits & 0x00000001u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *ssigheader_);
    }

    // optional bool pdwActiveState_nu = 383;
    if (cached_has_bits & 0x00000002u) {
      total_size += 2 + 1;
    }

    // optional uint32 uiVersionNumber = 2124;
    if (cached_has_bits & 0x00000004u) {
      total_size += 3 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_uiversionnumber());
    }

    // optional .pb.mf_drvwarnsm_core.dwfcore_state.DWFCoreState pdwCoreState_nu = 2651;
    if (cached_has_bits & 0x00000008u) {
      total_size += 3 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_pdwcorestate_nu());
    }

    // optional .pb.mf_drvwarnsm_core.dwfcore_state.DWFCoreState whpCoreState_nu = 3594;
    if (cached_has_bits & 0x00000010u) {
      total_size += 3 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_whpcorestate_nu());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DrvWarnCoreStatusPort::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
  GOOGLE_DCHECK_NE(&from, this);
  const DrvWarnCoreStatusPort* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DrvWarnCoreStatusPort>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
    MergeFrom(*source);
  }
}

void DrvWarnCoreStatusPort::MergeFrom(const DrvWarnCoreStatusPort& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_ssigheader()->::pb::eco::signal_header::SignalHeader::MergeFrom(from._internal_ssigheader());
    }
    if (cached_has_bits & 0x00000002u) {
      pdwactivestate_nu_ = from.pdwactivestate_nu_;
    }
    if (cached_has_bits & 0x00000004u) {
      uiversionnumber_ = from.uiversionnumber_;
    }
    if (cached_has_bits & 0x00000008u) {
      pdwcorestate_nu_ = from.pdwcorestate_nu_;
    }
    if (cached_has_bits & 0x00000010u) {
      whpcorestate_nu_ = from.whpcorestate_nu_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void DrvWarnCoreStatusPort::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DrvWarnCoreStatusPort::CopyFrom(const DrvWarnCoreStatusPort& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DrvWarnCoreStatusPort::IsInitialized() const {
  return true;
}

void DrvWarnCoreStatusPort::InternalSwap(DrvWarnCoreStatusPort* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(ssigheader_, other->ssigheader_);
  swap(pdwactivestate_nu_, other->pdwactivestate_nu_);
  swap(uiversionnumber_, other->uiversionnumber_);
  swap(pdwcorestate_nu_, other->pdwcorestate_nu_);
  swap(whpcorestate_nu_, other->whpcorestate_nu_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DrvWarnCoreStatusPort::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void DrvWarnCoreStatusPort_array_port::InitAsDefaultInstance() {
}
class DrvWarnCoreStatusPort_array_port::_Internal {
 public:
  using HasBits = decltype(std::declval<DrvWarnCoreStatusPort_array_port>()._has_bits_);
};

DrvWarnCoreStatusPort_array_port::DrvWarnCoreStatusPort_array_port()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
}
DrvWarnCoreStatusPort_array_port::DrvWarnCoreStatusPort_array_port(const DrvWarnCoreStatusPort_array_port& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      data_(from.data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
}

void DrvWarnCoreStatusPort_array_port::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DrvWarnCoreStatusPort_array_port_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto.base);
}

DrvWarnCoreStatusPort_array_port::~DrvWarnCoreStatusPort_array_port() {
  // @@protoc_insertion_point(destructor:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
  SharedDtor();
}

void DrvWarnCoreStatusPort_array_port::SharedDtor() {
}

void DrvWarnCoreStatusPort_array_port::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DrvWarnCoreStatusPort_array_port& DrvWarnCoreStatusPort_array_port::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DrvWarnCoreStatusPort_array_port_mf_5fdrvwarnsm_5fcore_2fdrv_5fwarn_5fcore_5fstatus_5fport_2eproto.base);
  return *internal_default_instance();
}


void DrvWarnCoreStatusPort_array_port::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* DrvWarnCoreStatusPort_array_port::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort data = 3371;
      case 3371:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_add_data(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DrvWarnCoreStatusPort_array_port::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort data = 3371;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_data_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3371, this->_internal_data(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
  return target;
}

size_t DrvWarnCoreStatusPort_array_port::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort data = 3371;
  total_size += 3UL * this->_internal_data_size();
  for (const auto& msg : this->data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DrvWarnCoreStatusPort_array_port::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
  GOOGLE_DCHECK_NE(&from, this);
  const DrvWarnCoreStatusPort_array_port* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DrvWarnCoreStatusPort_array_port>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
    MergeFrom(*source);
  }
}

void DrvWarnCoreStatusPort_array_port::MergeFrom(const DrvWarnCoreStatusPort_array_port& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
}

void DrvWarnCoreStatusPort_array_port::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DrvWarnCoreStatusPort_array_port::CopyFrom(const DrvWarnCoreStatusPort_array_port& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.mf_drvwarnsm_core.drv_warn_core_status_port.DrvWarnCoreStatusPort_array_port)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DrvWarnCoreStatusPort_array_port::IsInitialized() const {
  return true;
}

void DrvWarnCoreStatusPort_array_port::InternalSwap(DrvWarnCoreStatusPort_array_port* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  data_.InternalSwap(&other->data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DrvWarnCoreStatusPort_array_port::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace drv_warn_core_status_port
}  // namespace mf_drvwarnsm_core
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort* Arena::CreateMaybeMessage< ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort >(Arena* arena) {
  return Arena::CreateInternal< ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort_array_port* Arena::CreateMaybeMessage< ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort_array_port >(Arena* arena) {
  return Arena::CreateInternal< ::pb::mf_drvwarnsm_core::drv_warn_core_status_port::DrvWarnCoreStatusPort_array_port >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
