// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ap_commonvehsigprovider/odo_ext_ctrl_port.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "eco/signal_header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto;
namespace pb {
namespace ap_commonvehsigprovider {
namespace odo_ext_ctrl_port {
class OdoExtCtrlPort;
class OdoExtCtrlPortDefaultTypeInternal;
extern OdoExtCtrlPortDefaultTypeInternal _OdoExtCtrlPort_default_instance_;
class OdoExtCtrlPort_array_port;
class OdoExtCtrlPort_array_portDefaultTypeInternal;
extern OdoExtCtrlPort_array_portDefaultTypeInternal _OdoExtCtrlPort_array_port_default_instance_;
}  // namespace odo_ext_ctrl_port
}  // namespace ap_commonvehsigprovider
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort* Arena::CreateMaybeMessage<::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort>(Arena*);
template<> ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort_array_port* Arena::CreateMaybeMessage<::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort_array_port>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {
namespace ap_commonvehsigprovider {
namespace odo_ext_ctrl_port {

// ===================================================================

class OdoExtCtrlPort :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort) */ {
 public:
  OdoExtCtrlPort();
  virtual ~OdoExtCtrlPort();

  OdoExtCtrlPort(const OdoExtCtrlPort& from);
  OdoExtCtrlPort(OdoExtCtrlPort&& from) noexcept
    : OdoExtCtrlPort() {
    *this = ::std::move(from);
  }

  inline OdoExtCtrlPort& operator=(const OdoExtCtrlPort& from) {
    CopyFrom(from);
    return *this;
  }
  inline OdoExtCtrlPort& operator=(OdoExtCtrlPort&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OdoExtCtrlPort& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OdoExtCtrlPort* internal_default_instance() {
    return reinterpret_cast<const OdoExtCtrlPort*>(
               &_OdoExtCtrlPort_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OdoExtCtrlPort& a, OdoExtCtrlPort& b) {
    a.Swap(&b);
  }
  inline void Swap(OdoExtCtrlPort* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OdoExtCtrlPort* New() const final {
    return CreateMaybeMessage<OdoExtCtrlPort>(nullptr);
  }

  OdoExtCtrlPort* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OdoExtCtrlPort>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OdoExtCtrlPort& from);
  void MergeFrom(const OdoExtCtrlPort& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OdoExtCtrlPort* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto);
    return ::descriptor_table_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSSigHeaderFieldNumber = 1033,
    kUiVersionNumberFieldNumber = 2124,
    kResetPoseEstimationNuFieldNumber = 2299,
  };
  // optional .pb.eco.signal_header.SignalHeader sSigHeader = 1033;
  bool has_ssigheader() const;
  private:
  bool _internal_has_ssigheader() const;
  public:
  void clear_ssigheader();
  const ::pb::eco::signal_header::SignalHeader& ssigheader() const;
  ::pb::eco::signal_header::SignalHeader* release_ssigheader();
  ::pb::eco::signal_header::SignalHeader* mutable_ssigheader();
  void set_allocated_ssigheader(::pb::eco::signal_header::SignalHeader* ssigheader);
  private:
  const ::pb::eco::signal_header::SignalHeader& _internal_ssigheader() const;
  ::pb::eco::signal_header::SignalHeader* _internal_mutable_ssigheader();
  public:

  // optional uint32 uiVersionNumber = 2124;
  bool has_uiversionnumber() const;
  private:
  bool _internal_has_uiversionnumber() const;
  public:
  void clear_uiversionnumber();
  ::PROTOBUF_NAMESPACE_ID::uint32 uiversionnumber() const;
  void set_uiversionnumber(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_uiversionnumber() const;
  void _internal_set_uiversionnumber(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional bool resetPoseEstimation_nu = 2299;
  bool has_resetposeestimation_nu() const;
  private:
  bool _internal_has_resetposeestimation_nu() const;
  public:
  void clear_resetposeestimation_nu();
  bool resetposeestimation_nu() const;
  void set_resetposeestimation_nu(bool value);
  private:
  bool _internal_resetposeestimation_nu() const;
  void _internal_set_resetposeestimation_nu(bool value);
  public:

  // @@protoc_insertion_point(class_scope:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::pb::eco::signal_header::SignalHeader* ssigheader_;
  ::PROTOBUF_NAMESPACE_ID::uint32 uiversionnumber_;
  bool resetposeestimation_nu_;
  friend struct ::TableStruct_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto;
};
// -------------------------------------------------------------------

class OdoExtCtrlPort_array_port :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort_array_port) */ {
 public:
  OdoExtCtrlPort_array_port();
  virtual ~OdoExtCtrlPort_array_port();

  OdoExtCtrlPort_array_port(const OdoExtCtrlPort_array_port& from);
  OdoExtCtrlPort_array_port(OdoExtCtrlPort_array_port&& from) noexcept
    : OdoExtCtrlPort_array_port() {
    *this = ::std::move(from);
  }

  inline OdoExtCtrlPort_array_port& operator=(const OdoExtCtrlPort_array_port& from) {
    CopyFrom(from);
    return *this;
  }
  inline OdoExtCtrlPort_array_port& operator=(OdoExtCtrlPort_array_port&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OdoExtCtrlPort_array_port& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OdoExtCtrlPort_array_port* internal_default_instance() {
    return reinterpret_cast<const OdoExtCtrlPort_array_port*>(
               &_OdoExtCtrlPort_array_port_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(OdoExtCtrlPort_array_port& a, OdoExtCtrlPort_array_port& b) {
    a.Swap(&b);
  }
  inline void Swap(OdoExtCtrlPort_array_port* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OdoExtCtrlPort_array_port* New() const final {
    return CreateMaybeMessage<OdoExtCtrlPort_array_port>(nullptr);
  }

  OdoExtCtrlPort_array_port* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OdoExtCtrlPort_array_port>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OdoExtCtrlPort_array_port& from);
  void MergeFrom(const OdoExtCtrlPort_array_port& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OdoExtCtrlPort_array_port* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort_array_port";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto);
    return ::descriptor_table_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 991,
  };
  // repeated .pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort data = 991;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort >*
      mutable_data();
  private:
  const ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort& _internal_data(int index) const;
  ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort* _internal_add_data();
  public:
  const ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort& data(int index) const;
  ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort >&
      data() const;

  // @@protoc_insertion_point(class_scope:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort_array_port)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort > data_;
  friend struct ::TableStruct_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OdoExtCtrlPort

// optional uint32 uiVersionNumber = 2124;
inline bool OdoExtCtrlPort::_internal_has_uiversionnumber() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool OdoExtCtrlPort::has_uiversionnumber() const {
  return _internal_has_uiversionnumber();
}
inline void OdoExtCtrlPort::clear_uiversionnumber() {
  uiversionnumber_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OdoExtCtrlPort::_internal_uiversionnumber() const {
  return uiversionnumber_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OdoExtCtrlPort::uiversionnumber() const {
  // @@protoc_insertion_point(field_get:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort.uiVersionNumber)
  return _internal_uiversionnumber();
}
inline void OdoExtCtrlPort::_internal_set_uiversionnumber(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  uiversionnumber_ = value;
}
inline void OdoExtCtrlPort::set_uiversionnumber(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_uiversionnumber(value);
  // @@protoc_insertion_point(field_set:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort.uiVersionNumber)
}

// optional .pb.eco.signal_header.SignalHeader sSigHeader = 1033;
inline bool OdoExtCtrlPort::_internal_has_ssigheader() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || ssigheader_ != nullptr);
  return value;
}
inline bool OdoExtCtrlPort::has_ssigheader() const {
  return _internal_has_ssigheader();
}
inline const ::pb::eco::signal_header::SignalHeader& OdoExtCtrlPort::_internal_ssigheader() const {
  const ::pb::eco::signal_header::SignalHeader* p = ssigheader_;
  return p != nullptr ? *p : *reinterpret_cast<const ::pb::eco::signal_header::SignalHeader*>(
      &::pb::eco::signal_header::_SignalHeader_default_instance_);
}
inline const ::pb::eco::signal_header::SignalHeader& OdoExtCtrlPort::ssigheader() const {
  // @@protoc_insertion_point(field_get:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort.sSigHeader)
  return _internal_ssigheader();
}
inline ::pb::eco::signal_header::SignalHeader* OdoExtCtrlPort::release_ssigheader() {
  // @@protoc_insertion_point(field_release:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort.sSigHeader)
  _has_bits_[0] &= ~0x00000001u;
  ::pb::eco::signal_header::SignalHeader* temp = ssigheader_;
  ssigheader_ = nullptr;
  return temp;
}
inline ::pb::eco::signal_header::SignalHeader* OdoExtCtrlPort::_internal_mutable_ssigheader() {
  _has_bits_[0] |= 0x00000001u;
  if (ssigheader_ == nullptr) {
    auto* p = CreateMaybeMessage<::pb::eco::signal_header::SignalHeader>(GetArenaNoVirtual());
    ssigheader_ = p;
  }
  return ssigheader_;
}
inline ::pb::eco::signal_header::SignalHeader* OdoExtCtrlPort::mutable_ssigheader() {
  // @@protoc_insertion_point(field_mutable:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort.sSigHeader)
  return _internal_mutable_ssigheader();
}
inline void OdoExtCtrlPort::set_allocated_ssigheader(::pb::eco::signal_header::SignalHeader* ssigheader) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(ssigheader_);
  }
  if (ssigheader) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      ssigheader = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ssigheader, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  ssigheader_ = ssigheader;
  // @@protoc_insertion_point(field_set_allocated:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort.sSigHeader)
}

// optional bool resetPoseEstimation_nu = 2299;
inline bool OdoExtCtrlPort::_internal_has_resetposeestimation_nu() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool OdoExtCtrlPort::has_resetposeestimation_nu() const {
  return _internal_has_resetposeestimation_nu();
}
inline void OdoExtCtrlPort::clear_resetposeestimation_nu() {
  resetposeestimation_nu_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool OdoExtCtrlPort::_internal_resetposeestimation_nu() const {
  return resetposeestimation_nu_;
}
inline bool OdoExtCtrlPort::resetposeestimation_nu() const {
  // @@protoc_insertion_point(field_get:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort.resetPoseEstimation_nu)
  return _internal_resetposeestimation_nu();
}
inline void OdoExtCtrlPort::_internal_set_resetposeestimation_nu(bool value) {
  _has_bits_[0] |= 0x00000004u;
  resetposeestimation_nu_ = value;
}
inline void OdoExtCtrlPort::set_resetposeestimation_nu(bool value) {
  _internal_set_resetposeestimation_nu(value);
  // @@protoc_insertion_point(field_set:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort.resetPoseEstimation_nu)
}

// -------------------------------------------------------------------

// OdoExtCtrlPort_array_port

// repeated .pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort data = 991;
inline int OdoExtCtrlPort_array_port::_internal_data_size() const {
  return data_.size();
}
inline int OdoExtCtrlPort_array_port::data_size() const {
  return _internal_data_size();
}
inline void OdoExtCtrlPort_array_port::clear_data() {
  data_.Clear();
}
inline ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort* OdoExtCtrlPort_array_port::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort_array_port.data)
  return data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort >*
OdoExtCtrlPort_array_port::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort_array_port.data)
  return &data_;
}
inline const ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort& OdoExtCtrlPort_array_port::_internal_data(int index) const {
  return data_.Get(index);
}
inline const ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort& OdoExtCtrlPort_array_port::data(int index) const {
  // @@protoc_insertion_point(field_get:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort_array_port.data)
  return _internal_data(index);
}
inline ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort* OdoExtCtrlPort_array_port::_internal_add_data() {
  return data_.Add();
}
inline ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort* OdoExtCtrlPort_array_port::add_data() {
  // @@protoc_insertion_point(field_add:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort_array_port.data)
  return _internal_add_data();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::ap_commonvehsigprovider::odo_ext_ctrl_port::OdoExtCtrlPort >&
OdoExtCtrlPort_array_port::data() const {
  // @@protoc_insertion_point(field_list:pb.ap_commonvehsigprovider.odo_ext_ctrl_port.OdoExtCtrlPort_array_port.data)
  return data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace odo_ext_ctrl_port
}  // namespace ap_commonvehsigprovider
}  // namespace pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ap_5fcommonvehsigprovider_2fodo_5fext_5fctrl_5fport_2eproto
