//Attention, this file is generated by Cobolt from template: D:\.bbs_conan\c029a0\1\codegen\templates\types_c\enum.h.template!

#ifdef ECO_CPP_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C and C++ types mixed
  #endif
#endif
#ifdef ECO_CPP14_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C and C++14 types mixed
  #endif
#endif
#define ECO_C_TYPES_USED

#ifndef ECO_COMP_STAGE_C_H_
#define ECO_COMP_STAGE_C_H_

#include "Platform_Types.h"

///values: enum { INIT=0,SUSPEND=1,RESUME=2,SHUTDOWN=3
///,STAGE_UNDEFINED=255,}
///@range{0,255}
typedef uint8 ECO_CompStage;

#define ECO_COMP_STAGE_STAGE_INIT 0U
#define ECO_COMP_STAGE_STAGE_SUSPEND 1U
#define ECO_COMP_STAGE_STAGE_RESUME 2U
#define ECO_COMP_STAGE_STAGE_SHUTDOWN 3U
#define ECO_COMP_STAGE_STAGE_UNDEFINED 255U


#endif // ECO_COMP_STAGE_C_H_
