// Attention, this file is generated by Cobolt from template: D:\.bbs_conan\c029a0\1\codegen\templates\types_14\enum.h.template!

#ifdef ECO_C_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C and C++14 types mixed
  #endif
#endif
#ifdef ECO_CPP_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C++ and C++14 types mixed
  #endif
#endif
#define ECO_CPP14_TYPES_USED

#ifndef MF_HMIH_USER_DEFINED_SLOT_SIDE_H_
#define MF_HMIH_USER_DEFINED_SLOT_SIDE_H_

#include "Platform_Types.h"

namespace mf_hmih
{
  ///Keeps information abut the side where the user has defined a new slot.
  enum class UserDefinedSlotSide : uint8
  {
      USER_DEF_SIDE_CURRENT_EGO = 0U,
      USER_DEF_SIDE_RIGHT = 1U,
      USER_DEF_SIDE_LEFT = 2U,
      USER_DEF_SIDE_FRONT = 3U,
      USER_DEF_SIDE_REAR = 4U,
      USER_DEF_SIDE_NOT_VALID = 5U,
  };
} // namespace mf_hmih
#endif // MF_HMIH_USER_DEFINED_SLOT_SIDE_H_
