// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: us_drv/us_drv_dsi_packet_errors.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "us_drv/us_drv_error_status.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto;
namespace pb {
namespace us_drv {
namespace us_drv_dsi_packet_errors {
class UsDrvDsiPacketErrors;
class UsDrvDsiPacketErrorsDefaultTypeInternal;
extern UsDrvDsiPacketErrorsDefaultTypeInternal _UsDrvDsiPacketErrors_default_instance_;
class UsDrvDsiPacketErrors_array_port;
class UsDrvDsiPacketErrors_array_portDefaultTypeInternal;
extern UsDrvDsiPacketErrors_array_portDefaultTypeInternal _UsDrvDsiPacketErrors_array_port_default_instance_;
}  // namespace us_drv_dsi_packet_errors
}  // namespace us_drv
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors* Arena::CreateMaybeMessage<::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors>(Arena*);
template<> ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors_array_port* Arena::CreateMaybeMessage<::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors_array_port>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {
namespace us_drv {
namespace us_drv_dsi_packet_errors {

// ===================================================================

class UsDrvDsiPacketErrors :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors) */ {
 public:
  UsDrvDsiPacketErrors();
  virtual ~UsDrvDsiPacketErrors();

  UsDrvDsiPacketErrors(const UsDrvDsiPacketErrors& from);
  UsDrvDsiPacketErrors(UsDrvDsiPacketErrors&& from) noexcept
    : UsDrvDsiPacketErrors() {
    *this = ::std::move(from);
  }

  inline UsDrvDsiPacketErrors& operator=(const UsDrvDsiPacketErrors& from) {
    CopyFrom(from);
    return *this;
  }
  inline UsDrvDsiPacketErrors& operator=(UsDrvDsiPacketErrors&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UsDrvDsiPacketErrors& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UsDrvDsiPacketErrors* internal_default_instance() {
    return reinterpret_cast<const UsDrvDsiPacketErrors*>(
               &_UsDrvDsiPacketErrors_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UsDrvDsiPacketErrors& a, UsDrvDsiPacketErrors& b) {
    a.Swap(&b);
  }
  inline void Swap(UsDrvDsiPacketErrors* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UsDrvDsiPacketErrors* New() const final {
    return CreateMaybeMessage<UsDrvDsiPacketErrors>(nullptr);
  }

  UsDrvDsiPacketErrors* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UsDrvDsiPacketErrors>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UsDrvDsiPacketErrors& from);
  void MergeFrom(const UsDrvDsiPacketErrors& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UsDrvDsiPacketErrors* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto);
    return ::descriptor_table_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDsiPinUndervoltageFieldNumber = 764,
    kClkrefErrFieldNumber = 795,
    kSymbolCodingErrFieldNumber = 1147,
    kSymbolCountErrFieldNumber = 1887,
  };
  // optional .pb.us_drv.us_drv_error_status.UsDrvErrorStatus dsiPinUndervoltage = 764;
  bool has_dsipinundervoltage() const;
  private:
  bool _internal_has_dsipinundervoltage() const;
  public:
  void clear_dsipinundervoltage();
  ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus dsipinundervoltage() const;
  void set_dsipinundervoltage(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value);
  private:
  ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus _internal_dsipinundervoltage() const;
  void _internal_set_dsipinundervoltage(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value);
  public:

  // optional .pb.us_drv.us_drv_error_status.UsDrvErrorStatus clkrefErr = 795;
  bool has_clkreferr() const;
  private:
  bool _internal_has_clkreferr() const;
  public:
  void clear_clkreferr();
  ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus clkreferr() const;
  void set_clkreferr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value);
  private:
  ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus _internal_clkreferr() const;
  void _internal_set_clkreferr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value);
  public:

  // optional .pb.us_drv.us_drv_error_status.UsDrvErrorStatus symbolCodingErr = 1147;
  bool has_symbolcodingerr() const;
  private:
  bool _internal_has_symbolcodingerr() const;
  public:
  void clear_symbolcodingerr();
  ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus symbolcodingerr() const;
  void set_symbolcodingerr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value);
  private:
  ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus _internal_symbolcodingerr() const;
  void _internal_set_symbolcodingerr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value);
  public:

  // optional .pb.us_drv.us_drv_error_status.UsDrvErrorStatus symbolCountErr = 1887;
  bool has_symbolcounterr() const;
  private:
  bool _internal_has_symbolcounterr() const;
  public:
  void clear_symbolcounterr();
  ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus symbolcounterr() const;
  void set_symbolcounterr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value);
  private:
  ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus _internal_symbolcounterr() const;
  void _internal_set_symbolcounterr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value);
  public:

  // @@protoc_insertion_point(class_scope:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int dsipinundervoltage_;
  int clkreferr_;
  int symbolcodingerr_;
  int symbolcounterr_;
  friend struct ::TableStruct_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto;
};
// -------------------------------------------------------------------

class UsDrvDsiPacketErrors_array_port :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors_array_port) */ {
 public:
  UsDrvDsiPacketErrors_array_port();
  virtual ~UsDrvDsiPacketErrors_array_port();

  UsDrvDsiPacketErrors_array_port(const UsDrvDsiPacketErrors_array_port& from);
  UsDrvDsiPacketErrors_array_port(UsDrvDsiPacketErrors_array_port&& from) noexcept
    : UsDrvDsiPacketErrors_array_port() {
    *this = ::std::move(from);
  }

  inline UsDrvDsiPacketErrors_array_port& operator=(const UsDrvDsiPacketErrors_array_port& from) {
    CopyFrom(from);
    return *this;
  }
  inline UsDrvDsiPacketErrors_array_port& operator=(UsDrvDsiPacketErrors_array_port&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UsDrvDsiPacketErrors_array_port& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UsDrvDsiPacketErrors_array_port* internal_default_instance() {
    return reinterpret_cast<const UsDrvDsiPacketErrors_array_port*>(
               &_UsDrvDsiPacketErrors_array_port_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UsDrvDsiPacketErrors_array_port& a, UsDrvDsiPacketErrors_array_port& b) {
    a.Swap(&b);
  }
  inline void Swap(UsDrvDsiPacketErrors_array_port* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UsDrvDsiPacketErrors_array_port* New() const final {
    return CreateMaybeMessage<UsDrvDsiPacketErrors_array_port>(nullptr);
  }

  UsDrvDsiPacketErrors_array_port* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UsDrvDsiPacketErrors_array_port>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UsDrvDsiPacketErrors_array_port& from);
  void MergeFrom(const UsDrvDsiPacketErrors_array_port& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UsDrvDsiPacketErrors_array_port* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors_array_port";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto);
    return ::descriptor_table_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1342,
  };
  // repeated .pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors data = 1342;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors >*
      mutable_data();
  private:
  const ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors& _internal_data(int index) const;
  ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors* _internal_add_data();
  public:
  const ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors& data(int index) const;
  ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors >&
      data() const;

  // @@protoc_insertion_point(class_scope:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors_array_port)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors > data_;
  friend struct ::TableStruct_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UsDrvDsiPacketErrors

// optional .pb.us_drv.us_drv_error_status.UsDrvErrorStatus symbolCountErr = 1887;
inline bool UsDrvDsiPacketErrors::_internal_has_symbolcounterr() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool UsDrvDsiPacketErrors::has_symbolcounterr() const {
  return _internal_has_symbolcounterr();
}
inline void UsDrvDsiPacketErrors::clear_symbolcounterr() {
  symbolcounterr_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus UsDrvDsiPacketErrors::_internal_symbolcounterr() const {
  return static_cast< ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus >(symbolcounterr_);
}
inline ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus UsDrvDsiPacketErrors::symbolcounterr() const {
  // @@protoc_insertion_point(field_get:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors.symbolCountErr)
  return _internal_symbolcounterr();
}
inline void UsDrvDsiPacketErrors::_internal_set_symbolcounterr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value) {
  assert(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  symbolcounterr_ = value;
}
inline void UsDrvDsiPacketErrors::set_symbolcounterr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value) {
  _internal_set_symbolcounterr(value);
  // @@protoc_insertion_point(field_set:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors.symbolCountErr)
}

// optional .pb.us_drv.us_drv_error_status.UsDrvErrorStatus symbolCodingErr = 1147;
inline bool UsDrvDsiPacketErrors::_internal_has_symbolcodingerr() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool UsDrvDsiPacketErrors::has_symbolcodingerr() const {
  return _internal_has_symbolcodingerr();
}
inline void UsDrvDsiPacketErrors::clear_symbolcodingerr() {
  symbolcodingerr_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus UsDrvDsiPacketErrors::_internal_symbolcodingerr() const {
  return static_cast< ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus >(symbolcodingerr_);
}
inline ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus UsDrvDsiPacketErrors::symbolcodingerr() const {
  // @@protoc_insertion_point(field_get:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors.symbolCodingErr)
  return _internal_symbolcodingerr();
}
inline void UsDrvDsiPacketErrors::_internal_set_symbolcodingerr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value) {
  assert(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus_IsValid(value));
  _has_bits_[0] |= 0x00000004u;
  symbolcodingerr_ = value;
}
inline void UsDrvDsiPacketErrors::set_symbolcodingerr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value) {
  _internal_set_symbolcodingerr(value);
  // @@protoc_insertion_point(field_set:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors.symbolCodingErr)
}

// optional .pb.us_drv.us_drv_error_status.UsDrvErrorStatus dsiPinUndervoltage = 764;
inline bool UsDrvDsiPacketErrors::_internal_has_dsipinundervoltage() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool UsDrvDsiPacketErrors::has_dsipinundervoltage() const {
  return _internal_has_dsipinundervoltage();
}
inline void UsDrvDsiPacketErrors::clear_dsipinundervoltage() {
  dsipinundervoltage_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus UsDrvDsiPacketErrors::_internal_dsipinundervoltage() const {
  return static_cast< ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus >(dsipinundervoltage_);
}
inline ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus UsDrvDsiPacketErrors::dsipinundervoltage() const {
  // @@protoc_insertion_point(field_get:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors.dsiPinUndervoltage)
  return _internal_dsipinundervoltage();
}
inline void UsDrvDsiPacketErrors::_internal_set_dsipinundervoltage(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value) {
  assert(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  dsipinundervoltage_ = value;
}
inline void UsDrvDsiPacketErrors::set_dsipinundervoltage(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value) {
  _internal_set_dsipinundervoltage(value);
  // @@protoc_insertion_point(field_set:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors.dsiPinUndervoltage)
}

// optional .pb.us_drv.us_drv_error_status.UsDrvErrorStatus clkrefErr = 795;
inline bool UsDrvDsiPacketErrors::_internal_has_clkreferr() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool UsDrvDsiPacketErrors::has_clkreferr() const {
  return _internal_has_clkreferr();
}
inline void UsDrvDsiPacketErrors::clear_clkreferr() {
  clkreferr_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus UsDrvDsiPacketErrors::_internal_clkreferr() const {
  return static_cast< ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus >(clkreferr_);
}
inline ::pb::us_drv::us_drv_error_status::UsDrvErrorStatus UsDrvDsiPacketErrors::clkreferr() const {
  // @@protoc_insertion_point(field_get:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors.clkrefErr)
  return _internal_clkreferr();
}
inline void UsDrvDsiPacketErrors::_internal_set_clkreferr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value) {
  assert(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus_IsValid(value));
  _has_bits_[0] |= 0x00000002u;
  clkreferr_ = value;
}
inline void UsDrvDsiPacketErrors::set_clkreferr(::pb::us_drv::us_drv_error_status::UsDrvErrorStatus value) {
  _internal_set_clkreferr(value);
  // @@protoc_insertion_point(field_set:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors.clkrefErr)
}

// -------------------------------------------------------------------

// UsDrvDsiPacketErrors_array_port

// repeated .pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors data = 1342;
inline int UsDrvDsiPacketErrors_array_port::_internal_data_size() const {
  return data_.size();
}
inline int UsDrvDsiPacketErrors_array_port::data_size() const {
  return _internal_data_size();
}
inline void UsDrvDsiPacketErrors_array_port::clear_data() {
  data_.Clear();
}
inline ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors* UsDrvDsiPacketErrors_array_port::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors_array_port.data)
  return data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors >*
UsDrvDsiPacketErrors_array_port::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors_array_port.data)
  return &data_;
}
inline const ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors& UsDrvDsiPacketErrors_array_port::_internal_data(int index) const {
  return data_.Get(index);
}
inline const ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors& UsDrvDsiPacketErrors_array_port::data(int index) const {
  // @@protoc_insertion_point(field_get:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors_array_port.data)
  return _internal_data(index);
}
inline ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors* UsDrvDsiPacketErrors_array_port::_internal_add_data() {
  return data_.Add();
}
inline ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors* UsDrvDsiPacketErrors_array_port::add_data() {
  // @@protoc_insertion_point(field_add:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors_array_port.data)
  return _internal_add_data();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pb::us_drv::us_drv_dsi_packet_errors::UsDrvDsiPacketErrors >&
UsDrvDsiPacketErrors_array_port::data() const {
  // @@protoc_insertion_point(field_list:pb.us_drv.us_drv_dsi_packet_errors.UsDrvDsiPacketErrors_array_port.data)
  return data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace us_drv_dsi_packet_errors
}  // namespace us_drv
}  // namespace pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_us_5fdrv_2fus_5fdrv_5fdsi_5fpacket_5ferrors_2eproto
