// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: si/slot_surrounding_lines_serializable.proto

#include "si/slot_surrounding_lines_serializable.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_si_2fslot_5fsurrounding_5flines_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SlotSurroundingLines_si_2fslot_5fsurrounding_5flines_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SlotSurroundingLinesSerializable_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto;
namespace pb {
namespace si {
namespace slot_surrounding_lines_serializable {
class SlotSurroundingLinesSerializableDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SlotSurroundingLinesSerializable> _instance;
} _SlotSurroundingLinesSerializable_default_instance_;
class SlotSurroundingLinesSerializable_array_portDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SlotSurroundingLinesSerializable_array_port> _instance;
} _SlotSurroundingLinesSerializable_array_port_default_instance_;
}  // namespace slot_surrounding_lines_serializable
}  // namespace si
}  // namespace pb
static void InitDefaultsscc_info_SlotSurroundingLinesSerializable_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pb::si::slot_surrounding_lines_serializable::_SlotSurroundingLinesSerializable_default_instance_;
    new (ptr) ::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SlotSurroundingLinesSerializable_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_SlotSurroundingLinesSerializable_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto}, {
      &scc_info_SlotSurroundingLines_si_2fslot_5fsurrounding_5flines_2eproto.base,}};

static void InitDefaultsscc_info_SlotSurroundingLinesSerializable_array_port_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pb::si::slot_surrounding_lines_serializable::_SlotSurroundingLinesSerializable_array_port_default_instance_;
    new (ptr) ::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable_array_port();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable_array_port::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SlotSurroundingLinesSerializable_array_port_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_SlotSurroundingLinesSerializable_array_port_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto}, {
      &scc_info_SlotSurroundingLinesSerializable_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable, actualsize_),
  PROTOBUF_FIELD_OFFSET(::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable, array_),
  0,
  ~0u,
  PROTOBUF_FIELD_OFFSET(::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable_array_port, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable_array_port, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable_array_port, data_),
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable)},
  { 9, 15, sizeof(::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable_array_port)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::pb::si::slot_surrounding_lines_serializable::_SlotSurroundingLinesSerializable_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::pb::si::slot_surrounding_lines_serializable::_SlotSurroundingLinesSerializable_array_port_default_instance_),
};

const char descriptor_table_protodef_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n,si/slot_surrounding_lines_serializable"
  ".proto\022)pb.si.slot_surrounding_lines_ser"
  "ializable\032\037si/slot_surrounding_lines.pro"
  "to\"{\n SlotSurroundingLinesSerializable\022\023"
  "\n\nactualSize\030\301\027 \001(\r\022B\n\005array\030\347\n \003(\01322.pb"
  ".si.slot_surrounding_lines.SlotSurroundi"
  "ngLines\"\211\001\n+SlotSurroundingLinesSerializ"
  "able_array_port\022Z\n\004data\030\317\035 \003(\0132K.pb.si.s"
  "lot_surrounding_lines_serializable.SlotS"
  "urroundingLinesSerializable"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto_deps[1] = {
  &::descriptor_table_si_2fslot_5fsurrounding_5flines_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto_sccs[2] = {
  &scc_info_SlotSurroundingLinesSerializable_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto.base,
  &scc_info_SlotSurroundingLinesSerializable_array_port_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto_once;
static bool descriptor_table_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto = {
  &descriptor_table_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto_initialized, descriptor_table_protodef_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto, "si/slot_surrounding_lines_serializable.proto", 387,
  &descriptor_table_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto_once, descriptor_table_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto_sccs, descriptor_table_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto_deps, 2, 1,
  schemas, file_default_instances, TableStruct_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto::offsets,
  file_level_metadata_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto, 2, file_level_enum_descriptors_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto, file_level_service_descriptors_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto), true);
namespace pb {
namespace si {
namespace slot_surrounding_lines_serializable {

// ===================================================================

void SlotSurroundingLinesSerializable::InitAsDefaultInstance() {
}
class SlotSurroundingLinesSerializable::_Internal {
 public:
  using HasBits = decltype(std::declval<SlotSurroundingLinesSerializable>()._has_bits_);
  static void set_has_actualsize(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

void SlotSurroundingLinesSerializable::clear_array() {
  array_.Clear();
}
SlotSurroundingLinesSerializable::SlotSurroundingLinesSerializable()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
}
SlotSurroundingLinesSerializable::SlotSurroundingLinesSerializable(const SlotSurroundingLinesSerializable& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      array_(from.array_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  actualsize_ = from.actualsize_;
  // @@protoc_insertion_point(copy_constructor:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
}

void SlotSurroundingLinesSerializable::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SlotSurroundingLinesSerializable_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto.base);
  actualsize_ = 0u;
}

SlotSurroundingLinesSerializable::~SlotSurroundingLinesSerializable() {
  // @@protoc_insertion_point(destructor:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
  SharedDtor();
}

void SlotSurroundingLinesSerializable::SharedDtor() {
}

void SlotSurroundingLinesSerializable::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SlotSurroundingLinesSerializable& SlotSurroundingLinesSerializable::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SlotSurroundingLinesSerializable_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto.base);
  return *internal_default_instance();
}


void SlotSurroundingLinesSerializable::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  array_.Clear();
  actualsize_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* SlotSurroundingLinesSerializable::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .pb.si.slot_surrounding_lines.SlotSurroundingLines array = 1383;
      case 1383:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr -= 2;
          do {
            ptr += 2;
            ptr = ctx->ParseMessage(_internal_add_array(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<11066>(ptr));
        } else goto handle_unusual;
        continue;
      // optional uint32 actualSize = 3009;
      case 3009:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_actualsize(&has_bits);
          actualsize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SlotSurroundingLinesSerializable::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.si.slot_surrounding_lines.SlotSurroundingLines array = 1383;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_array_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1383, this->_internal_array(i), target, stream);
  }

  cached_has_bits = _has_bits_[0];
  // optional uint32 actualSize = 3009;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3009, this->_internal_actualsize(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
  return target;
}

size_t SlotSurroundingLinesSerializable::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pb.si.slot_surrounding_lines.SlotSurroundingLines array = 1383;
  total_size += 2UL * this->_internal_array_size();
  for (const auto& msg : this->array_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional uint32 actualSize = 3009;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 3 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_actualsize());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SlotSurroundingLinesSerializable::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
  GOOGLE_DCHECK_NE(&from, this);
  const SlotSurroundingLinesSerializable* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SlotSurroundingLinesSerializable>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
    MergeFrom(*source);
  }
}

void SlotSurroundingLinesSerializable::MergeFrom(const SlotSurroundingLinesSerializable& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  array_.MergeFrom(from.array_);
  if (from._internal_has_actualsize()) {
    _internal_set_actualsize(from._internal_actualsize());
  }
}

void SlotSurroundingLinesSerializable::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SlotSurroundingLinesSerializable::CopyFrom(const SlotSurroundingLinesSerializable& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SlotSurroundingLinesSerializable::IsInitialized() const {
  return true;
}

void SlotSurroundingLinesSerializable::InternalSwap(SlotSurroundingLinesSerializable* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  array_.InternalSwap(&other->array_);
  swap(actualsize_, other->actualsize_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SlotSurroundingLinesSerializable::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SlotSurroundingLinesSerializable_array_port::InitAsDefaultInstance() {
}
class SlotSurroundingLinesSerializable_array_port::_Internal {
 public:
  using HasBits = decltype(std::declval<SlotSurroundingLinesSerializable_array_port>()._has_bits_);
};

SlotSurroundingLinesSerializable_array_port::SlotSurroundingLinesSerializable_array_port()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
}
SlotSurroundingLinesSerializable_array_port::SlotSurroundingLinesSerializable_array_port(const SlotSurroundingLinesSerializable_array_port& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      data_(from.data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
}

void SlotSurroundingLinesSerializable_array_port::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SlotSurroundingLinesSerializable_array_port_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto.base);
}

SlotSurroundingLinesSerializable_array_port::~SlotSurroundingLinesSerializable_array_port() {
  // @@protoc_insertion_point(destructor:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
  SharedDtor();
}

void SlotSurroundingLinesSerializable_array_port::SharedDtor() {
}

void SlotSurroundingLinesSerializable_array_port::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SlotSurroundingLinesSerializable_array_port& SlotSurroundingLinesSerializable_array_port::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SlotSurroundingLinesSerializable_array_port_si_2fslot_5fsurrounding_5flines_5fserializable_2eproto.base);
  return *internal_default_instance();
}


void SlotSurroundingLinesSerializable_array_port::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* SlotSurroundingLinesSerializable_array_port::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable data = 3791;
      case 3791:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 122)) {
          ptr = ctx->ParseMessage(_internal_add_data(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SlotSurroundingLinesSerializable_array_port::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable data = 3791;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_data_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3791, this->_internal_data(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
  return target;
}

size_t SlotSurroundingLinesSerializable_array_port::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable data = 3791;
  total_size += 3UL * this->_internal_data_size();
  for (const auto& msg : this->data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SlotSurroundingLinesSerializable_array_port::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
  GOOGLE_DCHECK_NE(&from, this);
  const SlotSurroundingLinesSerializable_array_port* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SlotSurroundingLinesSerializable_array_port>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
    MergeFrom(*source);
  }
}

void SlotSurroundingLinesSerializable_array_port::MergeFrom(const SlotSurroundingLinesSerializable_array_port& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
}

void SlotSurroundingLinesSerializable_array_port::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SlotSurroundingLinesSerializable_array_port::CopyFrom(const SlotSurroundingLinesSerializable_array_port& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.si.slot_surrounding_lines_serializable.SlotSurroundingLinesSerializable_array_port)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SlotSurroundingLinesSerializable_array_port::IsInitialized() const {
  return true;
}

void SlotSurroundingLinesSerializable_array_port::InternalSwap(SlotSurroundingLinesSerializable_array_port* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  data_.InternalSwap(&other->data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SlotSurroundingLinesSerializable_array_port::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace slot_surrounding_lines_serializable
}  // namespace si
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable* Arena::CreateMaybeMessage< ::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable >(Arena* arena) {
  return Arena::CreateInternal< ::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable_array_port* Arena::CreateMaybeMessage< ::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable_array_port >(Arena* arena) {
  return Arena::CreateInternal< ::pb::si::slot_surrounding_lines_serializable::SlotSurroundingLinesSerializable_array_port >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
