# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ap_tp/target_pose.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lsm_geoml import pose_pod_pb2 as lsm__geoml_dot_pose__pod__pb2
from ap_tp import pose_type_pb2 as ap__tp_dot_pose__type__pb2
from ap_tp import target_side_pb2 as ap__tp_dot_target__side__pb2
from ap_tp import pose_reachable_status_pb2 as ap__tp_dot_pose__reachable__status__pb2
from ap_tp import pose_fail_reason_pb2 as ap__tp_dot_pose__fail__reason__pb2
from ap_tp import pose_obstacle_dist_pb2 as ap__tp_dot_pose__obstacle__dist__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ap_tp/target_pose.proto',
  package='pb.ap_tp.target_pose',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x17\x61p_tp/target_pose.proto\x12\x14pb.ap_tp.target_pose\x1a\x18lsm_geoml/pose_pod.proto\x1a\x15\x61p_tp/pose_type.proto\x1a\x17\x61p_tp/target_side.proto\x1a!ap_tp/pose_reachable_status.proto\x1a\x1c\x61p_tp/pose_fail_reason.proto\x1a\x1e\x61p_tp/pose_obstacle_dist.proto\"\xad\x03\n\nTargetPose\x12.\n\x04pose\x18\xe9\x0b \x01(\x0b\x32\x1f.pb.lsm_geoml.pose_pod.Pose_POD\x12\x10\n\x07pose_ID\x18\xd7\x14 \x01(\r\x12\x1c\n\x13relatedParkingBoxID\x18\xd7\x01 \x01(\r\x12+\n\x04type\x18\xb4\x1d \x01(\x0e\x32\x1c.pb.ap_tp.pose_type.PoseType\x12\x35\n\ntargetSide\x18\xfa\t \x01(\x0e\x32 .pb.ap_tp.target_side.TargetSide\x12M\n\x0freachableStatus\x18\xde\r \x01(\x0e\x32\x33.pb.ap_tp.pose_reachable_status.PoseReachableStatus\x12\x42\n\x0eposeFailReason\x18\x94\x13 \x01(\x0e\x32).pb.ap_tp.pose_fail_reason.PoseFailReason\x12H\n\x10poseObstacleDist\x18\xc2\x05 \x01(\x0b\x32-.pb.ap_tp.pose_obstacle_dist.PoseObstacleDist\"H\n\x15TargetPose_array_port\x12/\n\x04\x64\x61ta\x18\xbf\x1d \x03(\x0b\x32 .pb.ap_tp.target_pose.TargetPose'
  ,
  dependencies=[lsm__geoml_dot_pose__pod__pb2.DESCRIPTOR,ap__tp_dot_pose__type__pb2.DESCRIPTOR,ap__tp_dot_target__side__pb2.DESCRIPTOR,ap__tp_dot_pose__reachable__status__pb2.DESCRIPTOR,ap__tp_dot_pose__fail__reason__pb2.DESCRIPTOR,ap__tp_dot_pose__obstacle__dist__pb2.DESCRIPTOR,])




_TARGETPOSE = _descriptor.Descriptor(
  name='TargetPose',
  full_name='pb.ap_tp.target_pose.TargetPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='pb.ap_tp.target_pose.TargetPose.pose', index=0,
      number=1513, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose_ID', full_name='pb.ap_tp.target_pose.TargetPose.pose_ID', index=1,
      number=2647, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relatedParkingBoxID', full_name='pb.ap_tp.target_pose.TargetPose.relatedParkingBoxID', index=2,
      number=215, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='pb.ap_tp.target_pose.TargetPose.type', index=3,
      number=3764, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetSide', full_name='pb.ap_tp.target_pose.TargetPose.targetSide', index=4,
      number=1274, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reachableStatus', full_name='pb.ap_tp.target_pose.TargetPose.reachableStatus', index=5,
      number=1758, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='poseFailReason', full_name='pb.ap_tp.target_pose.TargetPose.poseFailReason', index=6,
      number=2452, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='poseObstacleDist', full_name='pb.ap_tp.target_pose.TargetPose.poseObstacleDist', index=7,
      number=706, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=650,
)


_TARGETPOSE_ARRAY_PORT = _descriptor.Descriptor(
  name='TargetPose_array_port',
  full_name='pb.ap_tp.target_pose.TargetPose_array_port',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='pb.ap_tp.target_pose.TargetPose_array_port.data', index=0,
      number=3775, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=724,
)

_TARGETPOSE.fields_by_name['pose'].message_type = lsm__geoml_dot_pose__pod__pb2._POSE_POD
_TARGETPOSE.fields_by_name['type'].enum_type = ap__tp_dot_pose__type__pb2._POSETYPE
_TARGETPOSE.fields_by_name['targetSide'].enum_type = ap__tp_dot_target__side__pb2._TARGETSIDE
_TARGETPOSE.fields_by_name['reachableStatus'].enum_type = ap__tp_dot_pose__reachable__status__pb2._POSEREACHABLESTATUS
_TARGETPOSE.fields_by_name['poseFailReason'].enum_type = ap__tp_dot_pose__fail__reason__pb2._POSEFAILREASON
_TARGETPOSE.fields_by_name['poseObstacleDist'].message_type = ap__tp_dot_pose__obstacle__dist__pb2._POSEOBSTACLEDIST
_TARGETPOSE_ARRAY_PORT.fields_by_name['data'].message_type = _TARGETPOSE
DESCRIPTOR.message_types_by_name['TargetPose'] = _TARGETPOSE
DESCRIPTOR.message_types_by_name['TargetPose_array_port'] = _TARGETPOSE_ARRAY_PORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TargetPose = _reflection.GeneratedProtocolMessageType('TargetPose', (_message.Message,), {
  'DESCRIPTOR' : _TARGETPOSE,
  '__module__' : 'ap_tp.target_pose_pb2'
  # @@protoc_insertion_point(class_scope:pb.ap_tp.target_pose.TargetPose)
  })
_sym_db.RegisterMessage(TargetPose)

TargetPose_array_port = _reflection.GeneratedProtocolMessageType('TargetPose_array_port', (_message.Message,), {
  'DESCRIPTOR' : _TARGETPOSE_ARRAY_PORT,
  '__module__' : 'ap_tp.target_pose_pb2'
  # @@protoc_insertion_point(class_scope:pb.ap_tp.target_pose.TargetPose_array_port)
  })
_sym_db.RegisterMessage(TargetPose_array_port)


# @@protoc_insertion_point(module_scope)
