// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: us_processing/us_processing_debug_port.proto

#include "us_processing/us_processing_debug_port.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_eco_2fsignal_5fheader_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SignalHeader_eco_2fsignal_5fheader_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_UsProcessingDebugPort_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_us_5fprocessing_2fus_5fprocessing_5ferrors_5fand_5fwarnings_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UsProcessingErrorsAndWarnings_us_5fprocessing_2fus_5fprocessing_5ferrors_5fand_5fwarnings_2eproto;
namespace pb {
namespace us_processing {
namespace us_processing_debug_port {
class UsProcessingDebugPortDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UsProcessingDebugPort> _instance;
} _UsProcessingDebugPort_default_instance_;
class UsProcessingDebugPort_array_portDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UsProcessingDebugPort_array_port> _instance;
} _UsProcessingDebugPort_array_port_default_instance_;
}  // namespace us_processing_debug_port
}  // namespace us_processing
}  // namespace pb
static void InitDefaultsscc_info_UsProcessingDebugPort_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pb::us_processing::us_processing_debug_port::_UsProcessingDebugPort_default_instance_;
    new (ptr) ::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_UsProcessingDebugPort_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_UsProcessingDebugPort_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto}, {
      &scc_info_SignalHeader_eco_2fsignal_5fheader_2eproto.base,
      &scc_info_UsProcessingErrorsAndWarnings_us_5fprocessing_2fus_5fprocessing_5ferrors_5fand_5fwarnings_2eproto.base,}};

static void InitDefaultsscc_info_UsProcessingDebugPort_array_port_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pb::us_processing::us_processing_debug_port::_UsProcessingDebugPort_array_port_default_instance_;
    new (ptr) ::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort_array_port();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort_array_port::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_UsProcessingDebugPort_array_port_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_UsProcessingDebugPort_array_port_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto}, {
      &scc_info_UsProcessingDebugPort_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort, uiversionnumber_),
  PROTOBUF_FIELD_OFFSET(::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort, ssigheader_),
  PROTOBUF_FIELD_OFFSET(::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort, usperrandwarnings_),
  2,
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort_array_port, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort_array_port, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort_array_port, data_),
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort)},
  { 11, 17, sizeof(::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort_array_port)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::pb::us_processing::us_processing_debug_port::_UsProcessingDebugPort_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::pb::us_processing::us_processing_debug_port::_UsProcessingDebugPort_array_port_default_instance_),
};

const char descriptor_table_protodef_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n,us_processing/us_processing_debug_port"
  ".proto\022)pb.us_processing.us_processing_d"
  "ebug_port\032\027eco/signal_header.proto\0325us_p"
  "rocessing/us_processing_errors_and_warni"
  "ngs.proto\"\331\001\n\025UsProcessingDebugPort\022\030\n\017u"
  "iVersionNumber\030\314\020 \001(\r\0227\n\nsSigHeader\030\211\010 \001"
  "(\0132\".pb.eco.signal_header.SignalHeader\022m"
  "\n\021uspErrAndWarnings\030\226\033 \001(\0132Q.pb.us_proce"
  "ssing.us_processing_errors_and_warnings."
  "UsProcessingErrorsAndWarnings\"r\n UsProce"
  "ssingDebugPort_array_port\022N\n\004data\0304 \003(\0132"
  "@.pb.us_processing.us_processing_debug_p"
  "ort.UsProcessingDebugPort"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto_deps[2] = {
  &::descriptor_table_eco_2fsignal_5fheader_2eproto,
  &::descriptor_table_us_5fprocessing_2fus_5fprocessing_5ferrors_5fand_5fwarnings_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto_sccs[2] = {
  &scc_info_UsProcessingDebugPort_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto.base,
  &scc_info_UsProcessingDebugPort_array_port_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto_once;
static bool descriptor_table_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto = {
  &descriptor_table_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto_initialized, descriptor_table_protodef_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto, "us_processing/us_processing_debug_port.proto", 505,
  &descriptor_table_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto_once, descriptor_table_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto_sccs, descriptor_table_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto_deps, 2, 2,
  schemas, file_default_instances, TableStruct_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto::offsets,
  file_level_metadata_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto, 2, file_level_enum_descriptors_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto, file_level_service_descriptors_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto), true);
namespace pb {
namespace us_processing {
namespace us_processing_debug_port {

// ===================================================================

void UsProcessingDebugPort::InitAsDefaultInstance() {
  ::pb::us_processing::us_processing_debug_port::_UsProcessingDebugPort_default_instance_._instance.get_mutable()->ssigheader_ = const_cast< ::pb::eco::signal_header::SignalHeader*>(
      ::pb::eco::signal_header::SignalHeader::internal_default_instance());
  ::pb::us_processing::us_processing_debug_port::_UsProcessingDebugPort_default_instance_._instance.get_mutable()->usperrandwarnings_ = const_cast< ::pb::us_processing::us_processing_errors_and_warnings::UsProcessingErrorsAndWarnings*>(
      ::pb::us_processing::us_processing_errors_and_warnings::UsProcessingErrorsAndWarnings::internal_default_instance());
}
class UsProcessingDebugPort::_Internal {
 public:
  using HasBits = decltype(std::declval<UsProcessingDebugPort>()._has_bits_);
  static void set_has_uiversionnumber(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::pb::eco::signal_header::SignalHeader& ssigheader(const UsProcessingDebugPort* msg);
  static void set_has_ssigheader(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::pb::us_processing::us_processing_errors_and_warnings::UsProcessingErrorsAndWarnings& usperrandwarnings(const UsProcessingDebugPort* msg);
  static void set_has_usperrandwarnings(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::pb::eco::signal_header::SignalHeader&
UsProcessingDebugPort::_Internal::ssigheader(const UsProcessingDebugPort* msg) {
  return *msg->ssigheader_;
}
const ::pb::us_processing::us_processing_errors_and_warnings::UsProcessingErrorsAndWarnings&
UsProcessingDebugPort::_Internal::usperrandwarnings(const UsProcessingDebugPort* msg) {
  return *msg->usperrandwarnings_;
}
void UsProcessingDebugPort::clear_ssigheader() {
  if (ssigheader_ != nullptr) ssigheader_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void UsProcessingDebugPort::clear_usperrandwarnings() {
  if (usperrandwarnings_ != nullptr) usperrandwarnings_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
UsProcessingDebugPort::UsProcessingDebugPort()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
}
UsProcessingDebugPort::UsProcessingDebugPort(const UsProcessingDebugPort& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._internal_has_ssigheader()) {
    ssigheader_ = new ::pb::eco::signal_header::SignalHeader(*from.ssigheader_);
  } else {
    ssigheader_ = nullptr;
  }
  if (from._internal_has_usperrandwarnings()) {
    usperrandwarnings_ = new ::pb::us_processing::us_processing_errors_and_warnings::UsProcessingErrorsAndWarnings(*from.usperrandwarnings_);
  } else {
    usperrandwarnings_ = nullptr;
  }
  uiversionnumber_ = from.uiversionnumber_;
  // @@protoc_insertion_point(copy_constructor:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
}

void UsProcessingDebugPort::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_UsProcessingDebugPort_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto.base);
  ::memset(&ssigheader_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&uiversionnumber_) -
      reinterpret_cast<char*>(&ssigheader_)) + sizeof(uiversionnumber_));
}

UsProcessingDebugPort::~UsProcessingDebugPort() {
  // @@protoc_insertion_point(destructor:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
  SharedDtor();
}

void UsProcessingDebugPort::SharedDtor() {
  if (this != internal_default_instance()) delete ssigheader_;
  if (this != internal_default_instance()) delete usperrandwarnings_;
}

void UsProcessingDebugPort::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UsProcessingDebugPort& UsProcessingDebugPort::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UsProcessingDebugPort_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto.base);
  return *internal_default_instance();
}


void UsProcessingDebugPort::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(ssigheader_ != nullptr);
      ssigheader_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(usperrandwarnings_ != nullptr);
      usperrandwarnings_->Clear();
    }
  }
  uiversionnumber_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* UsProcessingDebugPort::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .pb.eco.signal_header.SignalHeader sSigHeader = 1033;
      case 1033:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_ssigheader(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 uiVersionNumber = 2124;
      case 2124:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 96)) {
          _Internal::set_has_uiversionnumber(&has_bits);
          uiversionnumber_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .pb.us_processing.us_processing_errors_and_warnings.UsProcessingErrorsAndWarnings uspErrAndWarnings = 3478;
      case 3478:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 178)) {
          ptr = ctx->ParseMessage(_internal_mutable_usperrandwarnings(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UsProcessingDebugPort::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .pb.eco.signal_header.SignalHeader sSigHeader = 1033;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1033, _Internal::ssigheader(this), target, stream);
  }

  // optional uint32 uiVersionNumber = 2124;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2124, this->_internal_uiversionnumber(), target);
  }

  // optional .pb.us_processing.us_processing_errors_and_warnings.UsProcessingErrorsAndWarnings uspErrAndWarnings = 3478;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3478, _Internal::usperrandwarnings(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
  return target;
}

size_t UsProcessingDebugPort::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional .pb.eco.signal_header.SignalHeader sSigHeader = 1033;
    if (cached_has_bits & 0x00000001u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *ssigheader_);
    }

    // optional .pb.us_processing.us_processing_errors_and_warnings.UsProcessingErrorsAndWarnings uspErrAndWarnings = 3478;
    if (cached_has_bits & 0x00000002u) {
      total_size += 3 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *usperrandwarnings_);
    }

    // optional uint32 uiVersionNumber = 2124;
    if (cached_has_bits & 0x00000004u) {
      total_size += 3 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_uiversionnumber());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UsProcessingDebugPort::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
  GOOGLE_DCHECK_NE(&from, this);
  const UsProcessingDebugPort* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UsProcessingDebugPort>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
    MergeFrom(*source);
  }
}

void UsProcessingDebugPort::MergeFrom(const UsProcessingDebugPort& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_ssigheader()->::pb::eco::signal_header::SignalHeader::MergeFrom(from._internal_ssigheader());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_usperrandwarnings()->::pb::us_processing::us_processing_errors_and_warnings::UsProcessingErrorsAndWarnings::MergeFrom(from._internal_usperrandwarnings());
    }
    if (cached_has_bits & 0x00000004u) {
      uiversionnumber_ = from.uiversionnumber_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void UsProcessingDebugPort::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UsProcessingDebugPort::CopyFrom(const UsProcessingDebugPort& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UsProcessingDebugPort::IsInitialized() const {
  return true;
}

void UsProcessingDebugPort::InternalSwap(UsProcessingDebugPort* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(ssigheader_, other->ssigheader_);
  swap(usperrandwarnings_, other->usperrandwarnings_);
  swap(uiversionnumber_, other->uiversionnumber_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UsProcessingDebugPort::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void UsProcessingDebugPort_array_port::InitAsDefaultInstance() {
}
class UsProcessingDebugPort_array_port::_Internal {
 public:
  using HasBits = decltype(std::declval<UsProcessingDebugPort_array_port>()._has_bits_);
};

UsProcessingDebugPort_array_port::UsProcessingDebugPort_array_port()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
}
UsProcessingDebugPort_array_port::UsProcessingDebugPort_array_port(const UsProcessingDebugPort_array_port& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_),
      data_(from.data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
}

void UsProcessingDebugPort_array_port::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_UsProcessingDebugPort_array_port_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto.base);
}

UsProcessingDebugPort_array_port::~UsProcessingDebugPort_array_port() {
  // @@protoc_insertion_point(destructor:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
  SharedDtor();
}

void UsProcessingDebugPort_array_port::SharedDtor() {
}

void UsProcessingDebugPort_array_port::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UsProcessingDebugPort_array_port& UsProcessingDebugPort_array_port::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UsProcessingDebugPort_array_port_us_5fprocessing_2fus_5fprocessing_5fdebug_5fport_2eproto.base);
  return *internal_default_instance();
}


void UsProcessingDebugPort_array_port::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

const char* UsProcessingDebugPort_array_port::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .pb.us_processing.us_processing_debug_port.UsProcessingDebugPort data = 52;
      case 52:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          ptr -= 2;
          do {
            ptr += 2;
            ptr = ctx->ParseMessage(_internal_add_data(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<418>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UsProcessingDebugPort_array_port::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pb.us_processing.us_processing_debug_port.UsProcessingDebugPort data = 52;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_data_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(52, this->_internal_data(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
  return target;
}

size_t UsProcessingDebugPort_array_port::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pb.us_processing.us_processing_debug_port.UsProcessingDebugPort data = 52;
  total_size += 2UL * this->_internal_data_size();
  for (const auto& msg : this->data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UsProcessingDebugPort_array_port::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
  GOOGLE_DCHECK_NE(&from, this);
  const UsProcessingDebugPort_array_port* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UsProcessingDebugPort_array_port>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
    MergeFrom(*source);
  }
}

void UsProcessingDebugPort_array_port::MergeFrom(const UsProcessingDebugPort_array_port& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
}

void UsProcessingDebugPort_array_port::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UsProcessingDebugPort_array_port::CopyFrom(const UsProcessingDebugPort_array_port& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.us_processing.us_processing_debug_port.UsProcessingDebugPort_array_port)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UsProcessingDebugPort_array_port::IsInitialized() const {
  return true;
}

void UsProcessingDebugPort_array_port::InternalSwap(UsProcessingDebugPort_array_port* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  data_.InternalSwap(&other->data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UsProcessingDebugPort_array_port::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace us_processing_debug_port
}  // namespace us_processing
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort* Arena::CreateMaybeMessage< ::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort >(Arena* arena) {
  return Arena::CreateInternal< ::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort >(arena);
}
template<> PROTOBUF_NOINLINE ::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort_array_port* Arena::CreateMaybeMessage< ::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort_array_port >(Arena* arena) {
  return Arena::CreateInternal< ::pb::us_processing::us_processing_debug_port::UsProcessingDebugPort_array_port >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
