// Attention, this file is generated by Cobolt from template: D:\.bbs_conan\c029a0\1\codegen\templates\types\generated_types.h.template!

#ifdef ECO_C_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C and C++ types mixed
  #endif
#endif
#ifdef ECO_CPP14_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C++ and C++14 types mixed
  #endif
#endif
#define ECO_CPP_TYPES_USED

#ifndef US_PROCESSING_GENERATED_TYPES_H_
#define US_PROCESSING_GENERATED_TYPES_H_

#include "us_processing/us_processing_consts.h"
#include "us_processing/us_processing_sns_mode.h"
#include "us_processing/us_processing_measurement_status.h"
#include "us_processing/us_processing_sensor_status.h"
#include "us_processing/us_processing_sensor_running_mode.h"
#include "us_processing/us_processing_object_type.h"
#include "us_processing/us_processing_object_height.h"
#include "us_processing/us_processing_object_kinematic.h"
#include "us_processing/us_processing_func_input.h"
#include "us_processing/us_processing_func_input_interface_version.h"
#include "us_processing/us_processing_vertex.h"
#include "us_processing/us_processing_point.h"
#include "us_processing/us_processing_object.h"
#include "us_processing/us_processing_point_list.h"
#include "us_processing/us_processing_point_list_interface_version.h"
#include "us_processing/us_processing_object_list.h"
#include "us_processing/us_processing_object_list_interface_version.h"
#include "us_processing/us_processing_diag_output.h"
#include "us_processing/us_processing_diag_output_interface_version.h"
#include "us_processing/us_processing_distance_list.h"
#include "us_processing/us_processing_distance_list_interface_version.h"
#include "us_processing/us_processing_data_integrity.h"
#include "us_processing/us_processing_data_integrity_interface_version.h"
#include "us_processing/us_processing_filtered_echo.h"
#include "us_processing/us_processing_filtered_echo_list.h"
#include "us_processing/us_processing_filtered_echo_list_interface_version.h"
#include "us_processing/us_processing_errors_and_warnings.h"
#include "us_processing/us_processing_debug_port.h"
#include "us_processing/us_processing_debug_port_interface_version.h"
#include "us_processing/us_processing_sensor_parameter.h"
#include "us_processing/us_processing_sensor_parameters.h"
#include "us_processing/us_processing_state_management_cfg.h"
#include "us_processing/us_processing_echo_pre_processing_cfg.h"
#include "us_processing/us_processing_reflection_tracking_cfg.h"
#include "us_processing/us_processing_neighboring_filter_cfg.h"
#include "us_processing/us_processing_object_tracking_cfg.h"
#include "us_processing/us_processing_dyn_params.h"
#include "us_processing/us_processing_params.h"
#include "us_processing/us_processing_params_interface_version.h"

#endif // US_PROCESSING_GENERATED_TYPES_H_
