//Attention, this file is generated by Cobolt from template: D:\.bbs_conan\c029a0\1\codegen\templates\types_c\enum.h.template!

#ifdef ECO_CPP_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C and C++ types mixed
  #endif
#endif
#ifdef ECO_CPP14_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C and C++14 types mixed
  #endif
#endif
#define ECO_C_TYPES_USED

#ifndef AP_PSM_APP_STD_REQUEST_C_H_
#define AP_PSM_APP_STD_REQUEST_C_H_

#include "Platform_Types.h"

typedef uint8 AP_PSM_APP_StdRequest;

#define AP_PSM_APP_STD_REQUEST_STD_REQ_NO_REQUEST 0U
#define AP_PSM_APP_STD_REQUEST_STD_REQ_INIT 1U
#define AP_PSM_APP_STD_REQUEST_STD_REQ_SCAN 2U
#define AP_PSM_APP_STD_REQUEST_STD_REQ_PREPARE 3U
#define AP_PSM_APP_STD_REQUEST_STD_REQ_DEGRADE 4U
#define AP_PSM_APP_STD_REQUEST_STD_REQ_START 5U
#define AP_PSM_APP_STD_REQUEST_STD_REQ_PAUSE 6U
#define AP_PSM_APP_STD_REQUEST_STD_REQ_SECURE 7U
#define AP_PSM_APP_STD_REQUEST_STD_REQ_FINISH 8U
#define AP_PSM_APP_STD_REQUEST_STD_REQ_ERROR 9U


#endif // AP_PSM_APP_STD_REQUEST_C_H_
