# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mf_hmih/fc_mfhmih_params.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from eco import signal_header_pb2 as eco_dot_signal__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mf_hmih/fc_mfhmih_params.proto',
  package='pb.mf_hmih.fc_mfhmih_params',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1emf_hmih/fc_mfhmih_params.proto\x12\x1bpb.mf_hmih.fc_mfhmih_params\x1a\x17\x65\x63o/signal_header.proto\"\xad\x05\n\x10\x46\x43_MFHMIH_Params\x12\x18\n\x0fuiVersionNumber\x18\xcc\x10 \x01(\r\x12\x37\n\nsSigHeader\x18\x89\x08 \x01(\x0b\x32\".pb.eco.signal_header.SignalHeader\x12$\n\x1b\x41P_H_OBSTACLE_MIN_PAR_HMI_M\x18\x98\x1a \x01(\x02\x12$\n\x1b\x41P_H_OBSTACLE_MAX_PAR_HMI_M\x18\xf9\x04 \x01(\x02\x12%\n\x1c\x41P_H_OBSTACLE_MIN_PERP_HMI_M\x18\xb7\x03 \x01(\x02\x12%\n\x1c\x41P_H_OBSTACLE_MAX_PERP_HMI_M\x18\x83\r \x01(\x02\x12\'\n\x1f\x41P_H_FWDBWD_SLOT_DIST_MAX_HMI_M\x18\x0c \x01(\x02\x12%\n\x1c\x41P_H_FIRST_SLOT_HMI_OFFSET_M\x18\x8d\x1f \x01(\x02\x12(\n\x1f\x41P_H_PERPAR_SLOT_DIST_MAX_HMI_M\x18\xea\x0b \x01(\x02\x12(\n\x1f\x41P_H_USER_DEF_INIT_LAT_OFFSET_M\x18\x81\x03 \x01(\x02\x12%\n\x1c\x41P_H_USER_DEF_SLIDE_OFFSET_M\x18\xe1\x1e \x01(\x02\x12%\n\x1c\x41P_H_USER_DEF_ANG_OFFSET_RAD\x18\xb6\x03 \x01(\x02\x12&\n\x1d\x41P_H_USER_DEF_MAX_ANG_PAR_RAD\x18\xe2\x08 \x01(\x02\x12\'\n\x1e\x41P_H_USER_DEF_MAX_ANG_PERP_RAD\x18\xc6\x13 \x01(\x02\x12!\n\x18\x41P_H_USER_DEF_ENABLED_NU\x18\xa1\x1e \x01(\x08\x12\x1e\n\x15\x41P_H_CUSTOMER_DEMO_NU\x18\xbc\x0e \x01(\x08\x12&\n\x1d\x41P_H_EXPLICIT_SCAN_ENABLED_NU\x18\xae\x1a \x01(\x08\"[\n\x1b\x46\x43_MFHMIH_Params_array_port\x12<\n\x04\x64\x61ta\x18\xa5\x03 \x03(\x0b\x32-.pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params'
  ,
  dependencies=[eco_dot_signal__header__pb2.DESCRIPTOR,])




_FC_MFHMIH_PARAMS = _descriptor.Descriptor(
  name='FC_MFHMIH_Params',
  full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uiVersionNumber', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.uiVersionNumber', index=0,
      number=2124, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sSigHeader', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.sSigHeader', index=1,
      number=1033, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_OBSTACLE_MIN_PAR_HMI_M', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_OBSTACLE_MIN_PAR_HMI_M', index=2,
      number=3352, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_OBSTACLE_MAX_PAR_HMI_M', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_OBSTACLE_MAX_PAR_HMI_M', index=3,
      number=633, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_OBSTACLE_MIN_PERP_HMI_M', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_OBSTACLE_MIN_PERP_HMI_M', index=4,
      number=439, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_OBSTACLE_MAX_PERP_HMI_M', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_OBSTACLE_MAX_PERP_HMI_M', index=5,
      number=1667, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_FWDBWD_SLOT_DIST_MAX_HMI_M', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_FWDBWD_SLOT_DIST_MAX_HMI_M', index=6,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_FIRST_SLOT_HMI_OFFSET_M', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_FIRST_SLOT_HMI_OFFSET_M', index=7,
      number=3981, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_PERPAR_SLOT_DIST_MAX_HMI_M', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_PERPAR_SLOT_DIST_MAX_HMI_M', index=8,
      number=1514, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_USER_DEF_INIT_LAT_OFFSET_M', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_USER_DEF_INIT_LAT_OFFSET_M', index=9,
      number=385, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_USER_DEF_SLIDE_OFFSET_M', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_USER_DEF_SLIDE_OFFSET_M', index=10,
      number=3937, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_USER_DEF_ANG_OFFSET_RAD', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_USER_DEF_ANG_OFFSET_RAD', index=11,
      number=438, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_USER_DEF_MAX_ANG_PAR_RAD', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_USER_DEF_MAX_ANG_PAR_RAD', index=12,
      number=1122, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_USER_DEF_MAX_ANG_PERP_RAD', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_USER_DEF_MAX_ANG_PERP_RAD', index=13,
      number=2502, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_USER_DEF_ENABLED_NU', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_USER_DEF_ENABLED_NU', index=14,
      number=3873, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_CUSTOMER_DEMO_NU', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_CUSTOMER_DEMO_NU', index=15,
      number=1852, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AP_H_EXPLICIT_SCAN_ENABLED_NU', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params.AP_H_EXPLICIT_SCAN_ENABLED_NU', index=16,
      number=3374, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=774,
)


_FC_MFHMIH_PARAMS_ARRAY_PORT = _descriptor.Descriptor(
  name='FC_MFHMIH_Params_array_port',
  full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params_array_port',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params_array_port.data', index=0,
      number=421, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=776,
  serialized_end=867,
)

_FC_MFHMIH_PARAMS.fields_by_name['sSigHeader'].message_type = eco_dot_signal__header__pb2._SIGNALHEADER
_FC_MFHMIH_PARAMS_ARRAY_PORT.fields_by_name['data'].message_type = _FC_MFHMIH_PARAMS
DESCRIPTOR.message_types_by_name['FC_MFHMIH_Params'] = _FC_MFHMIH_PARAMS
DESCRIPTOR.message_types_by_name['FC_MFHMIH_Params_array_port'] = _FC_MFHMIH_PARAMS_ARRAY_PORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FC_MFHMIH_Params = _reflection.GeneratedProtocolMessageType('FC_MFHMIH_Params', (_message.Message,), {
  'DESCRIPTOR' : _FC_MFHMIH_PARAMS,
  '__module__' : 'mf_hmih.fc_mfhmih_params_pb2'
  # @@protoc_insertion_point(class_scope:pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params)
  })
_sym_db.RegisterMessage(FC_MFHMIH_Params)

FC_MFHMIH_Params_array_port = _reflection.GeneratedProtocolMessageType('FC_MFHMIH_Params_array_port', (_message.Message,), {
  'DESCRIPTOR' : _FC_MFHMIH_PARAMS_ARRAY_PORT,
  '__module__' : 'mf_hmih.fc_mfhmih_params_pb2'
  # @@protoc_insertion_point(class_scope:pb.mf_hmih.fc_mfhmih_params.FC_MFHMIH_Params_array_port)
  })
_sym_db.RegisterMessage(FC_MFHMIH_Params_array_port)


# @@protoc_insertion_point(module_scope)
