// Attention, this file is generated by Cobolt from template: D:\.bbs_conan\c029a0\1\codegen\templates\types_14\struct.h.template!

#ifdef ECO_C_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C and C++14 types mixed
  #endif
#endif
#ifdef ECO_CPP_TYPES_USED
  #ifndef ECO_ALLOW_INTERFACE_MIXING
    #error eco C++ and C++14 types mixed
  #endif
#endif
#define ECO_CPP14_TYPES_USED

#ifndef AP_COMMONVEHSIGPROVIDER_GEAR_INFORMATION_H_
#define AP_COMMONVEHSIGPROVIDER_GEAR_INFORMATION_H_

#include "ap_commonvehsigprovider/gear_box_ctrl_system_state.h"
#include "ap_commonvehsigprovider/gear.h"


namespace ap_commonvehsigprovider
{

  /// None
  struct GearInformation
  {
    ///@range{0,7}
    ///System status/Availability of the gearbox control.
    GearBoxCtrlSystemState gearboxCtrlSystemState_nu{};
    ///@range{0,15}
    ///System status/Availability of the gearbox control and current gear.
    Gear gearCur_nu{};
  };

} // namespace ap_commonvehsigprovider

#endif // AP_COMMONVEHSIGPROVIDER_GEAR_INFORMATION_H_
